import axios from 'axios';

export type PersonType = 'PF' | 'PJ';
export type PersonStatus = 'ACTIVE' | 'INACTIVE';
export interface PersonSummary { id: number; personType: PersonType; displayName: string; document: string | null; contactCount: number; status: PersonStatus; }
export interface PeoplePage { people: PersonSummary[]; pagination: { page: number; perPage: number; total: number; lastPage: number }; }
export interface PersonContactWrite { contactType: 'EMAIL' | 'PHONE' | 'MOBILE' | 'WHATSAPP' | 'WEBSITE' | 'OTHER'; value: string; description?: string | null; }
export interface PersonPixKeyWrite { keyType: 'CPF' | 'CNPJ' | 'EMAIL' | 'PHONE' | 'RANDOM'; value: string; status?: PersonStatus; }
export interface PersonRelationshipWrite { idTargetPerson: number; relationshipType: 'CHILD_OF' | 'PARENT_OF' | 'GRANDCHILD_OF' | 'GRANDPARENT_OF' | 'SPOUSE_OF' | 'PARTNER_OF' | 'EMPLOYEE_OF' | 'EMPLOYER_OF' | 'CONTRACTOR_OF' | 'CONTRACTING_PARTY_OF' | 'OTHER'; description?: string | null; }
export interface PersonAddressWrite { label: string; addressType: 'RESIDENTIAL' | 'COMMERCIAL' | 'BILLING' | 'DELIVERY' | 'BRANCH' | 'OTHER'; idCountry: number; idBrazilState?: number | null; idBrazilMunicipality?: number | null; idLocalityReference?: number | null; stateText?: string | null; cityText?: string | null; street?: string | null; number?: string | null; complement?: string | null; district?: string | null; reference?: string | null; postalCode?: string | null; }
export interface PersonBankAccountWrite { label: string; idFinancialInstitution?: number | null; accountType: 'CHECKING' | 'SAVINGS' | 'INVESTMENT' | 'SALARY' | 'OTHER'; agency?: string | null; agencyDigit?: string | null; accountNumber?: string | null; accountDigit?: string | null; status?: PersonStatus; }
export interface PersonDetail extends PersonSummary { name: string; alias: string | null; cpf: string | null; cnpj: string | null; rg: string | null; rgIssuer: string | null; pisNis: string | null; passportNumber: string | null; foreignDocumentNumber: string | null; birthDate: string | null; foundationDate: string | null; notes: string | null; version: number; addresses: PersonAddressWrite[]; contacts: PersonContactWrite[]; bankAccounts: PersonBankAccountWrite[]; pixKeys: PersonPixKeyWrite[]; relationships: (PersonRelationshipWrite & { id?: number; direction?: string; displayRelationshipType?: string; idOtherPerson?: number })[]; }
export interface PersonWrite { personType: PersonType; name: string; alias?: string | null; cpf?: string | null; cnpj?: string | null; rg?: string | null; rgIssuer?: string |null; pisNis?: string | null; passportNumber?: string | null; foreignDocumentNumber?: string | null; birthDate?: string | null; foundationDate?: string | null; notes?: string | null; addresses?: PersonAddressWrite[]; contacts?: PersonContactWrite[]; bankAccounts?: PersonBankAccountWrite[]; pixKeys?: PersonPixKeyWrite[]; relationships?: PersonRelationshipWrite[]; }

function idempotencyKey(): string { return globalThis.crypto?.randomUUID?.() ?? `00000000-0000-4000-8000-${Date.now().toString().padStart(12, '0').slice(-12)}`; }
export async function loadPeople(tenantId: number, query: Record<string, unknown>): Promise<PeoplePage> { return (await axios.get(`/api/v1/tenants/${tenantId}/people`, { params: query })).data as PeoplePage; }
export async function loadPerson(tenantId: number, personId: number): Promise<PersonDetail> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/${personId}`)).data.person as PersonDetail; }
export async function createPerson(tenantId: number, payload: PersonWrite): Promise<PersonDetail> { return (await axios.post(`/api/v1/tenants/${tenantId}/people`, payload, { headers: { 'Idempotency-Key': idempotencyKey() } })).data.person as PersonDetail; }
export async function updatePerson(tenantId: number, personId: number, version: number, payload: PersonWrite): Promise<PersonDetail> { return (await axios.put(`/api/v1/tenants/${tenantId}/people/${personId}`, { ...payload, version }, { headers: { 'Idempotency-Key': idempotencyKey() } })).data.person as PersonDetail; }
export async function duplicatePerson(tenantId: number, personId: number, version: number, options: { copyAddresses: boolean; copyContacts: boolean; copyBankAccounts: boolean; copyPixKeys: boolean }): Promise<PersonDetail> { return (await axios.post(`/api/v1/tenants/${tenantId}/people/${personId}/duplicate`, { ...options, version }, { headers: { 'Idempotency-Key': idempotencyKey() } })).data.person as PersonDetail; }
export async function changePersonStatus(tenantId: number, personId: number, version: number, status: 'inactivate' | 'reactivate'): Promise<PersonDetail> { return (await axios.post(`/api/v1/tenants/${tenantId}/people/${personId}/${status}`, { version }, { headers: { 'Idempotency-Key': idempotencyKey() } })).data.person as PersonDetail; }
export async function deletionUsage(tenantId: number, personId: number): Promise<{ module: string; description: string }[]> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/${personId}/deletion-usage`)).data.usages; }
export async function deletePerson(tenantId: number, personId: number, version: number): Promise<void> { await axios.delete(`/api/v1/tenants/${tenantId}/people/${personId}`, { data: { version }, headers: { 'Idempotency-Key': idempotencyKey() } }); }
export async function loadCountries(tenantId: number): Promise<{id:number;isoAlpha2:string;name:string}[]> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/references/countries`)).data.countries; }
export async function loadBrazilStates(tenantId: number, countryId: number): Promise<{id:number;abbreviation:string;name:string}[]> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/references/countries/${countryId}/brazil-states`)).data.states; }
export async function loadBrazilMunicipalities(tenantId: number, stateId: number): Promise<{id:number;name:string}[]> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/references/brazil-states/${stateId}/municipalities`)).data.municipalities; }
export async function loadFinancialInstitutions(tenantId: number, search = ''): Promise<{id:number;name:string;code:string|null}[]> { return (await axios.get(`/api/v1/tenants/${tenantId}/people/references/financial-institutions`, { params: { search } })).data.financialInstitutions; }
export interface PostalReferenceCandidate { id: number; streetType: string | null; streetName: string | null; neighborhoodName: string | null; }
export async function lookupPostalReferences(countryCode: string, postalCode: string): Promise<PostalReferenceCandidate[]> { return (await axios.post('/api/v1/localities/postal-references/lookup', { countryCode, postalCode })).data.candidates as PostalReferenceCandidate[]; }
