<script setup lang="ts">
import axios from 'axios';
import { computed, nextTick, onMounted, onUnmounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import AccessFrame from './design-system/AccessFrame.vue';
import AuthenticatedFrame from './design-system/AuthenticatedFrame.vue';
import UiAlert from './design-system/UiAlert.vue';
import UiButton from './design-system/UiButton.vue';
import UiField from './design-system/UiField.vue';
import ToastHost from './design-system/toast/ToastHost.vue';
import DialogHost from './design-system/dialog/DialogHost.vue';

type PublicView = 'login' | 'register';
type ChallengePurpose = 'register' | 'passwordless';
const { t } = useI18n();
const publicView = ref<PublicView>(window.location.pathname === '/access/register' ? 'register' : 'login');
const email = ref(''); const password = ref(''); const createDisplayName = ref(''); const rememberMe = ref(false); const processing = ref(false);
const message = ref(''); const feedbackKind = ref<'success' | 'error'>('success'); const emailError = ref(''); const displayNameError = ref('');
const challengeId = ref<number | null>(null); const challengePurpose = ref<ChallengePurpose>('passwordless'); const code = ref(''); const linkToken = ref<string | null>(null);
const security = ref(false); const session = ref<{ user: { displayName: string; passwordDefined: boolean }; persistentAuthentication: boolean } | null>(null);
const remainingSeconds = ref(0); const resendCooldownSeconds = ref(0); const offline = ref(!navigator.onLine);
const emailInput = ref<HTMLInputElement | null>(null); const displayNameInput = ref<HTMLInputElement | null>(null); const codeInput = ref<HTMLInputElement | null>(null); let expiryTimer: number | undefined; let resendTimer: number | undefined;
const remainingLabel = computed(() => `${Math.floor(remainingSeconds.value / 60)}:${String(remainingSeconds.value % 60).padStart(2, '0')}`);
const resendCooldownLabel = computed(() => `${Math.floor(resendCooldownSeconds.value / 60)}:${String(resendCooldownSeconds.value % 60).padStart(2, '0')}`);
const resendActionLabel = computed(() => resendCooldownSeconds.value > 0 ? t('access.actions.resendMessageIn', { time: resendCooldownLabel.value }) : t('access.actions.resendMessage'));
const loginActionLabel = computed(() => password.value ? t('access.actions.enter') : t('access.actions.sendAccessCode'));
function setFeedback(value: string, kind: 'success' | 'error') { message.value = value; feedbackKind.value = kind; }
function validEmail() { return /^\S+@\S+\.\S+$/.test(email.value); }
function normalizeCode(event: Event) { code.value = (event.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, 6); }
function startExpiry() { remainingSeconds.value = 600; window.clearInterval(expiryTimer); expiryTimer = window.setInterval(() => { if (remainingSeconds.value > 0) remainingSeconds.value -= 1; if (!remainingSeconds.value) { window.clearInterval(expiryTimer); setFeedback(t('access.feedback.codeExpired'), 'error'); } }, 1000); }
function startResendCooldown(seconds: unknown) { resendCooldownSeconds.value = Math.max(0, Math.ceil(Number(seconds) || 0)); window.clearInterval(resendTimer); if (resendCooldownSeconds.value > 0) resendTimer = window.setInterval(() => { resendCooldownSeconds.value = Math.max(0, resendCooldownSeconds.value - 1); if (!resendCooldownSeconds.value) window.clearInterval(resendTimer); }, 1000); }
function retryAfterSeconds(error: unknown): number { return axios.isAxiosError(error) ? Number(error.response?.headers?.['retry-after'] ?? 0) : 0; }
async function focusCurrentField() { await nextTick(); if (!challengeId.value) { (publicView.value === 'register' ? displayNameInput : emailInput).value?.focus(); return; } if (!linkToken.value) { codeInput.value?.focus(); return; } if (challengePurpose.value === 'register') displayNameInput.value?.focus(); }
function navigate(view: PublicView, replace = false) { publicView.value = view; email.value = ''; password.value = ''; message.value = ''; emailError.value = ''; displayNameError.value = ''; const path = view === 'register' ? '/access/register' : '/'; window.history[replace ? 'replaceState' : 'pushState']({}, '', path); void focusCurrentField(); }
function apiError(error: unknown, fallback: string) {
    if (!axios.isAxiosError(error)) return fallback;

    switch (error.response?.data?.code) {
    case 'INVALID_CREDENTIAL': return t('access.feedback.invalidCredential');
    case 'RATE_LIMITED': return t('access.feedback.authenticationRateLimited');
    default: return fallback;
    }
}
async function submitLogin() { emailError.value = ''; message.value = ''; if (!validEmail()) { emailError.value = t('access.feedback.emailInvalid'); return; } if (offline.value) { setFeedback(t('access.offline'), 'error'); return; } processing.value = true; try { const isPasswordLogin = Boolean(password.value); const response = await axios.post(isPasswordLogin ? '/api/v1/auth/password-sessions' : '/api/v1/auth/passwordless-sessions', isPasswordLogin ? { email: email.value, password: password.value, rememberMe: rememberMe.value } : { email: email.value, rememberMe: rememberMe.value }); if (response.data.user) { setFeedback(t('access.feedback.accessSuccess'), 'success'); security.value = true; await loadSession(); return; } setFeedback(t('access.feedback.passwordlessRequestAccepted', { email: email.value }), 'success'); startResendCooldown(response.data.resendAvailableInSeconds); challengePurpose.value = 'passwordless'; challengeId.value = response.data.challengeId ?? null; if (challengeId.value) { startExpiry(); await focusCurrentField(); } } catch (error) { const retryAfter = retryAfterSeconds(error); if (retryAfter) startResendCooldown(retryAfter); setFeedback(apiError(error, retryAfter ? t('access.feedback.resendCooldown', { time: resendCooldownLabel.value }) : t('access.feedback.requestFailed')), 'error'); } finally { processing.value = false; } }
async function submitRegistration() { emailError.value = ''; displayNameError.value = ''; message.value = ''; if (!createDisplayName.value.trim()) { displayNameError.value = t('access.feedback.displayNameRequired'); return; } if (!validEmail()) { emailError.value = t('access.feedback.emailInvalid'); return; } if (offline.value) { setFeedback(t('access.offline'), 'error'); return; } processing.value = true; try { const response = await axios.post('/api/v1/auth/registrations', { email: email.value, displayName: createDisplayName.value.trim(), rememberMe: false }); challengePurpose.value = 'register'; challengeId.value = response.data.challengeId ?? null; setFeedback(t('access.feedback.verificationSent'), 'success'); startResendCooldown(response.data.resendAvailableInSeconds); if (challengeId.value) { startExpiry(); await focusCurrentField(); } } catch (error) { const retryAfter = retryAfterSeconds(error); if (retryAfter) startResendCooldown(retryAfter); setFeedback(apiError(error, retryAfter ? t('access.feedback.resendCooldown', { time: resendCooldownLabel.value }) : t('access.feedback.requestFailed')), 'error'); } finally { processing.value = false; } }
async function confirm() { if (!challengeId.value || offline.value) return; processing.value = true; try { const isRegister = challengePurpose.value === 'register'; const path = linkToken.value ? (isRegister ? '/api/v1/auth/email-verifications/link-confirmations' : '/api/v1/auth/passwordless-sessions/link-confirmations') : (isRegister ? '/api/v1/auth/email-verifications' : '/api/v1/auth/passwordless-sessions/confirmations'); const payload = linkToken.value ? { challengeId: challengeId.value, token: linkToken.value } : { challengeId: challengeId.value, code: code.value }; await axios.post(path, payload); security.value = true; challengeId.value = null; linkToken.value = null; setFeedback(t('access.feedback.accessSuccess'), 'success'); await loadSession(); } catch (error) { setFeedback(axios.isAxiosError(error) && error.response?.status === 400 ? t('access.feedback.confirmationInvalid') : t('access.feedback.confirmationFailed'), 'error'); await focusCurrentField(); } finally { processing.value = false; } }
async function resend() { if (resendCooldownSeconds.value > 0) return; if (challengePurpose.value === 'register') await submitRegistration(); else await submitLogin(); }
async function loadSession() { try { session.value = (await axios.get('/api/v1/auth/session')).data; security.value = true; } catch { security.value = false; } }
async function logout() { if (offline.value) return; await axios.delete('/api/v1/auth/session'); security.value = false; session.value = null; navigate('login', true); }
function online() { offline.value = false; } function offlineEvent() { offline.value = true; }
function updatePublicViewFromPath() { publicView.value = window.location.pathname === '/access/register' ? 'register' : 'login'; }
onMounted(async () => { window.addEventListener('online', online); window.addEventListener('offline', offlineEvent); window.addEventListener('popstate', updatePublicViewFromPath); await loadSession(); if (security.value) return; const query = new URLSearchParams(window.location.search); const id = query.get('challengeId'); const token = query.get('token'); const numericId = id === null ? NaN : Number(id); if (Number.isSafeInteger(numericId) && numericId > 0 && token) { challengeId.value = numericId; linkToken.value = token; challengePurpose.value = window.location.pathname.includes('passwordless') ? 'passwordless' : 'register'; startExpiry(); window.history.replaceState({}, '', window.location.pathname); } await focusCurrentField(); if (linkToken.value) await confirm(); });
onUnmounted(() => { window.clearInterval(expiryTimer); window.clearInterval(resendTimer); window.removeEventListener('online', online); window.removeEventListener('offline', offlineEvent); window.removeEventListener('popstate', updatePublicViewFromPath); });
</script>

<template>
    <AccessFrame v-if="!security">
        <template v-if="!challengeId">
            <h1 id="access-title" class="access-card-title" tabindex="-1">{{ publicView === 'login' ? t('access.entryTitle') : t('access.createTitle') }}</h1>
            <form v-if="publicView === 'login'" class="access-form" novalidate @submit.prevent="submitLogin"><UiField id="email" :label="t('access.fields.email')" :error="emailError" required v-slot="field"><input id="email" ref="emailInput" v-model.trim="email" type="email" autocomplete="email" :aria-describedby="field.describedBy" :aria-invalid="field.invalid" required></UiField><UiField id="password" :label="t('access.fields.password')" v-slot="field"><input id="password" v-model="password" type="password" autocomplete="current-password" :aria-describedby="field.describedBy"></UiField><label><input v-model="rememberMe" type="checkbox"> {{ t('access.fields.rememberMe') }}</label><UiAlert v-if="offline" tone="warning">{{ t('access.offline') }}</UiAlert><UiAlert v-if="message" :tone="feedbackKind === 'error' ? 'error' : 'success'">{{ message }}</UiAlert><UiButton type="submit" :loading="processing" :disabled="offline">{{ processing ? t('access.actions.processing') : loginActionLabel }}</UiButton><button type="button" class="access-link" @click="navigate('register')">{{ t('access.createAccountLink') }}</button></form>
            <form v-else class="access-form" novalidate @submit.prevent="submitRegistration"><UiField id="display-name" :label="t('access.fields.displayName')" :error="displayNameError" required v-slot="field"><input id="display-name" ref="displayNameInput" v-model.trim="createDisplayName" autocomplete="name" :aria-describedby="field.describedBy" :aria-invalid="field.invalid" required></UiField><UiField id="email" :label="t('access.fields.email')" :error="emailError" required v-slot="field"><input id="email" ref="emailInput" v-model.trim="email" type="email" autocomplete="email" :aria-describedby="field.describedBy" :aria-invalid="field.invalid" required></UiField><UiAlert v-if="offline" tone="warning">{{ t('access.offline') }}</UiAlert><UiAlert v-if="message" :tone="feedbackKind === 'error' ? 'error' : 'success'">{{ message }}</UiAlert><UiButton type="submit" :loading="processing" :disabled="offline">{{ processing ? t('access.actions.processing') : t('access.actions.createAccount') }}</UiButton><button type="button" class="access-link" @click="navigate('login')">{{ t('access.haveAccount') }}</button></form>
        </template>
        <form v-else class="access-form" @submit.prevent="confirm"><h1 class="access-card-title">{{ t('access.confirmation.title') }}</h1><p>{{ t('access.confirmation.body') }} <span aria-live="off">{{ t('access.confirmation.validFor', { time: remainingLabel }) }}</span></p><p v-if="challengePurpose === 'register'" class="access-confirmation-email">{{ t('access.confirmation.sentTo', { email }) }}</p><UiField v-if="!linkToken" id="code" :label="t('access.fields.code')" v-slot="field"><input id="code" ref="codeInput" :value="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" :aria-describedby="field.describedBy" required @input="normalizeCode"></UiField><UiAlert v-if="offline" tone="warning">{{ t('access.offline') }}</UiAlert><UiAlert v-if="message" :tone="feedbackKind === 'error' ? 'error' : 'success'">{{ message }}</UiAlert><UiButton type="submit" :loading="processing" :disabled="offline || remainingSeconds === 0">{{ t('access.actions.completeAccess') }}</UiButton><UiButton v-if="!linkToken" variant="secondary" :disabled="processing || offline || resendCooldownSeconds > 0" @click="resend">{{ resendActionLabel }}</UiButton></form>
    </AccessFrame>
    <AuthenticatedFrame v-else :display-name="session?.user.displayName" @profile-updated="session && (session.user.displayName = $event.user.displayName)" @sign-out="logout" />
    <ToastHost :has-top-bar="security" />
    <DialogHost />
</template>
