import type { AccessMessages } from './types';

export const en: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Access your account', createTitle: 'Create account', haveAccount: 'I already have an account', createAccountLink: 'Create account', entryDescription: 'Create an account or choose how you want to sign in.',
        offline: 'You are offline. Actions will be available when the connection returns.', modeLabel: 'Access mode',
        modes: { register: 'Create account', password: 'Sign in', passwordless: 'Passwordless' },
        fields: { email: 'Email', password: 'Password', rememberMe: 'Keep me signed in', code: 'Confirmation code', displayName: 'Name', newPassword: 'New password' },
        actions: { processing: 'Processing…', createAccount: 'Create account', enter: 'Sign in', sendAccessCode: 'Sign in without password', confirming: 'Confirming…', confirmLink: 'Confirm link', completeAccess: 'Complete access', resendMessage: 'Resend message', returnToAccess: 'Back to access', definePassword: 'Set password', savePassword: 'Save password', invalidateOthers: 'Invalidate other sessions', endSession: 'End this session', cancel: 'Cancel', invalidateSessions: 'Invalidate sessions' },
        confirmation: { title: 'Confirm your email', body: 'Enter the 6-digit code sent in the message.', validFor: 'Valid for {time}.', remembered: 'You chose to stay signed in on this browser.' },
        security: { title: 'Access security', greeting: 'Hello, {name}.', passwordDefined: 'Password set.', passwordOptional: 'You can set an optional password.', passwordHelp: 'At least 6 characters and two categories: lowercase, uppercase, number, or symbol.', sessions: 'Sessions', persistent: 'You will stay signed in on this browser.', active: 'Current session active.', invalidateTitle: 'Invalidate other sessions?', invalidateDescription: 'Other browsers and devices will need to sign in again.' },
        presentation: { visualPreferences: 'Visual preferences', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', textDensity: 'Text density', spacing: 'Spacing', componentSize: 'Element size', compact: 'Compact', default: 'Default', comfortable: 'Comfortable', large: 'Large', selectedLanguage: 'Current language: {language}' },
        shell: { menu: 'Personal menu', avatar: 'Personal menu for {name}', userSettings: 'User settings', settingsUnavailable: 'Available soon', signOut: 'Sign out', openNavigation: 'Open navigation', closeNavigation: 'Close navigation', navigation: 'Navigation', emptyNavigation: 'No additional area is available at this stage.' },
        feedback: { emailInvalid: 'Enter a valid email address.', displayNameRequired: 'Enter a display name.', verificationSent: 'Check your email to continue.', codeExpired: 'This code has expired. Request a new message to continue.', accessSuccess: 'Access completed successfully.', requestFailed: 'We could not complete this action.', confirmationFailed: 'We could not confirm this code.', confirmationInvalid: 'This code or link is no longer valid. Request a new message to continue.', confirmationRateLimited: 'This action cannot be completed now. Wait a few minutes and try again.', passwordCriteria: 'The password does not meet the requirements: at least 6 characters and two categories.', passwordRequired: 'Enter a password to continue.', passwordSet: 'Password set.', invalidateFailed: 'We could not invalidate the other sessions.', invalidateSuccess: 'Other sessions were invalidated.' },
    },
};
