import type { AccessMessages } from './types';

export const en: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Access your account', createTitle: 'Create account', haveAccount: 'I already have an account', createAccountLink: 'Create account', entryDescription: 'Create an account or choose how you want to sign in.',
        offline: 'You are offline. Actions will be available when the connection returns.', modeLabel: 'Access mode',
        modes: { register: 'Create account', password: 'Sign in', passwordless: 'Passwordless' },
        fields: { email: 'Email', password: 'Password', rememberMe: 'Keep me signed in', code: 'Confirmation code', displayName: 'Name', newPassword: 'New password' },
        actions: { processing: 'Processing…', createAccount: 'Create account', enter: 'Sign in', sendAccessCode: 'Sign in without password', confirming: 'Confirming…', confirmLink: 'Confirm link', completeAccess: 'Complete access', resendMessage: 'Resend message', returnToAccess: 'Back to access', definePassword: 'Set password', savePassword: 'Save password', invalidateOthers: 'Invalidate other sessions', endSession: 'End this session', cancel: 'Cancel', invalidateSessions: 'Invalidate sessions' },
        confirmation: { title: 'Confirm your email', body: 'Enter the 6-digit code sent in the message.', validFor: 'Valid for {time}.', remembered: 'You chose to stay signed in on this browser.' },
        security: { title: 'Access security', greeting: 'Hello, {name}.', passwordDefined: 'Password set.', passwordOptional: 'You can set an optional password.', passwordHelp: 'At least 6 characters and two categories: lowercase, uppercase, number, or symbol.', sessions: 'Sessions', persistent: 'You will stay signed in on this browser.', active: 'Current session active.', invalidateTitle: 'Invalidate other sessions?', invalidateDescription: 'Other browsers and devices will need to sign in again.' },
        presentation: { visualPreferences: 'Visual preferences', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', textDensity: 'Text density', spacing: 'Spacing', componentSize: 'Element size', compact: 'Compact', default: 'Default', comfortable: 'Comfortable', large: 'Large', selectedLanguage: 'Current language: {language}' },
        shell: { menu: 'Personal menu', avatar: 'Personal menu for {name}', userSettings: 'User settings', settingsUnavailable: 'Available soon', signOut: 'Sign out', openNavigation: 'Open navigation', closeNavigation: 'Close navigation', navigation: 'Navigation', emptyNavigation: 'No additional area is available at this stage.' },
        workspace: { title: 'Workspace', emptyTitle: 'Your workspace is ready', emptyDescription: 'Open navigation to access the areas available to you.', navigation: { title: 'Navigation', collapse: 'Collapse navigation', expand: 'Expand navigation', empty: 'No area is available at this stage.' }, surface: { unavailableTitle: 'This surface is no longer available', unavailableDescription: 'Return to navigation to choose an available area.', readyDescription: 'This surface is ready to receive approved content.' }, taskbar: { label: 'Open surfaces', close: 'Close', dirty: 'Unsaved changes' }, mobile: { noSurfaces: 'No surface is open.' }, dialog: { discardTitle: 'Unsaved changes', discardDescription: 'There is unconfirmed work. Do you want to discard the changes?', informationTitle: 'Information', informationDescription: 'Information is available.', warningTitle: 'Attention', warningDescription: 'This action requires your attention.', errorTitle: 'Error', errorDescription: 'We could not complete this action.', confirmationTitle: 'Confirmation', confirmationDescription: 'Confirm the action to continue.', close: 'Close', cancel: 'Cancel', discard: 'Discard changes' }, notification: { dismiss: 'Dismiss notification', contextChanged: 'Surfaces from the previous organization were closed.', demoReady: 'Demonstration notification displayed successfully.' } },
        tenant: { title: 'Organizations', managementTitle: 'Organizations', selectAvatar: 'Select organization', currentAvatar: 'Current organization: {name}', current: 'Context:', noneSelected: 'None selected', name: 'Organization name', nameRequired: 'Enter the organization name.', nameTooLong: 'The name must be at most 120 characters.', loading: 'Loading organizations…', empty: 'You do not belong to any organization.', personalSpace: 'Use only my space', create: 'Create organization', manage: 'Manage organizations', more: 'More organizations', searchTitle: 'All organizations', searchPlaceholder: 'Filter organizations', searchResults: 'Organization results', searchEmpty: 'No organizations found.', close: 'Close organization selector', selected: 'Active organization: {name}.', personalSelected: 'You are using only your personal space.', creationAccepted: 'The organization is being prepared.', createFailed: 'We could not create this organization.', availabilityChanged: 'Availability was updated.', availabilityFailed: 'We could not update availability.', enable: 'Enable', disable: 'Disable', disableConfirmationTitle: 'Disable organization?', disableConfirmationDescription: 'The organization {name} cannot be selected until it is enabled again.', states: { PROVISIONING: 'Preparing', ACTIVE: 'Active', INACTIVE: 'Disabled', FAILED: 'Unavailable' }, offline: 'You are offline. Try again when the connection returns.', loadFailed: 'We could not load organizations.', selectFailed: 'We could not select this organization.', endFailed: 'We could not end this context.' },
        feedback: { emailInvalid: 'Enter a valid email address.', displayNameRequired: 'Enter a display name.', verificationSent: 'Check your email to continue.', codeExpired: 'This code has expired. Request a new message to continue.', accessSuccess: 'Access completed successfully.', requestFailed: 'We could not complete this action.', confirmationFailed: 'We could not confirm this code.', confirmationInvalid: 'This code or link is no longer valid. Request a new message to continue.', confirmationRateLimited: 'This action cannot be completed now. Wait a few minutes and try again.', passwordCriteria: 'The password does not meet the requirements: at least 6 characters and two categories.', passwordRequired: 'Enter a password to continue.', passwordSet: 'Password set.', invalidateFailed: 'We could not invalidate the other sessions.', invalidateSuccess: 'Other sessions were invalidated.' },
    },
};
