import type { AccessMessages } from './types';

export const en: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Access your account', createTitle: 'Create account', haveAccount: 'I already have an account', createAccountLink: 'Create account', entryDescription: 'Create an account or choose how you want to sign in.',
        offline: 'You are offline. Actions will be available when the connection returns.', modeLabel: 'Access mode',
        modes: { register: 'Create account', password: 'Sign in', passwordless: 'Passwordless' },
        fields: { email: 'Email', password: 'Password', rememberMe: 'Keep me signed in', code: 'Confirmation code', displayName: 'Name', newPassword: 'New password' },
        actions: { processing: 'Processing…', createAccount: 'Create account', enter: 'Sign in', sendAccessCode: 'Sign in without password', confirming: 'Confirming…', confirmLink: 'Confirm link', completeAccess: 'Complete access', resendMessage: 'Resend message', resendMessageIn: 'Resend in {time}', returnToAccess: 'Back to access', definePassword: 'Set password', savePassword: 'Save password', invalidateOthers: 'Invalidate other sessions', endSession: 'End this session', cancel: 'Cancel', invalidateSessions: 'Invalidate sessions' },
        confirmation: { title: 'Confirm your email', body: 'Enter the 6-digit code sent in the message.', validFor: 'Valid for {time}.', remembered: 'You chose to stay signed in on this browser.' },
        security: { title: 'Access security', greeting: 'Hello, {name}.', passwordDefined: 'Password set.', passwordOptional: 'You can set an optional password.', passwordHelp: 'At least 6 characters and two categories: lowercase, uppercase, number, or symbol.', sessions: 'Sessions', persistent: 'You will stay signed in on this browser.', active: 'Current session active.', invalidateTitle: 'Invalidate other sessions?', invalidateDescription: 'Other browsers and devices will need to sign in again.' },
        presentation: { visualPreferences: 'Visual preferences', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', textDensity: 'Text density', spacing: 'Spacing', componentSize: 'Element size', compact: 'Compact', default: 'Default', comfortable: 'Comfortable', large: 'Large', selectedLanguage: 'Current language: {language}' },
        shell: { menu: 'Personal menu', avatar: 'Personal menu for {name}', userSettings: 'User settings', settingsUnavailable: 'Available soon', signOut: 'Sign out', openNavigation: 'Open navigation', closeNavigation: 'Close navigation', navigation: 'Navigation', emptyNavigation: 'No additional area is available at this stage.' },
        workspace: { title: 'Workspace', emptyTitle: 'Your workspace is ready', emptyDescription: 'Open navigation to access the areas available to you.', navigation: { title: 'Navigation', collapse: 'Collapse navigation', expand: 'Expand navigation', empty: 'No area is available at this stage.' }, surface: { unavailableTitle: 'This surface is no longer available', unavailableDescription: 'Return to navigation to choose an available area.', readyDescription: 'This surface is ready to receive approved content.' }, taskbar: { label: 'Open surfaces', close: 'Close', dirty: 'Unsaved changes' }, mobile: { noSurfaces: 'No surface is open.' }, dialog: { discardTitle: 'Unsaved changes', discardDescription: 'There is unconfirmed work. Do you want to discard the changes?', informationTitle: 'Information', informationDescription: 'Information is available.', warningTitle: 'Attention', warningDescription: 'This action requires your attention.', errorTitle: 'Error', errorDescription: 'We could not complete this action.', confirmationTitle: 'Confirmation', confirmationDescription: 'Confirm the action to continue.', close: 'Close', cancel: 'Cancel', discard: 'Discard changes' }, notification: { dismiss: 'Dismiss notification', contextChanged: 'Surfaces from the previous organization were closed.' } },
        tenant: { title: 'Organizations', managementTitle: 'Organizations', selectAvatar: 'Select organization', currentAvatar: 'Current organization: {name}', current: 'Context:', noneSelected: 'None selected', name: 'Organization name', nameRequired: 'Enter the organization name.', nameTooLong: 'The name must be at most 120 characters.', loading: 'Loading organizations…', empty: 'You do not belong to any organization.', personalSpace: 'Use only my space', create: 'Create organization', manage: 'Manage organizations', more: 'More organizations', searchTitle: 'All organizations', searchPlaceholder: 'Filter organizations', searchResults: 'Organization results', searchEmpty: 'No organizations found.', close: 'Close organization selector', selected: 'Active organization: {name}.', personalSelected: 'You are using only your personal space.', creationAccepted: 'The organization is being prepared.', createFailed: 'We could not create this organization.', availabilityChanged: 'Availability was updated.', availabilityFailed: 'We could not update availability.', enable: 'Enable', disable: 'Disable', disableConfirmationTitle: 'Disable organization?', disableConfirmationDescription: 'The organization {name} cannot be selected until it is enabled again.', states: { PROVISIONING: 'Preparing', ACTIVE: 'Active', INACTIVE: 'Disabled', FAILED: 'Unavailable' }, offline: 'You are offline. Try again when the connection returns.', loadFailed: 'We could not load organizations.', selectFailed: 'We could not select this organization.', endFailed: 'We could not end this context.' },
        feedback: { emailInvalid: 'Enter a valid email address.', displayNameRequired: 'Enter a display name.', verificationSent: 'Check your email to continue.', passwordlessRequestAccepted: 'If an account exists for {email}, we will send a passwordless access email.', resendCooldown: 'Wait {time} before requesting another message.', codeExpired: 'This code has expired. Request a new message to continue.', accessSuccess: 'Access completed successfully.', requestFailed: 'We could not complete this action.', invalidCredential: 'Invalid email or password.', authenticationRateLimited: 'Too many sign-in attempts. Wait a few minutes and try again.', confirmationFailed: 'We could not confirm this code.', confirmationInvalid: 'This code or link is no longer valid. Request a new message to continue.', confirmationRateLimited: 'This action cannot be completed now. Wait a few minutes and try again.', passwordCriteria: 'The password does not meet the requirements: at least 6 characters and two categories.', passwordRequired: 'Enter a password to continue.', passwordSet: 'Password set.', invalidateFailed: 'We could not invalidate the other sessions.', invalidateSuccess: 'Other sessions were invalidated.' },
    },
};

Object.assign(en.access, { maintenance: { eyebrow: 'Platform administration', title: 'Maintenance Hub', reload: 'Reload', loading: 'Loading routines…', empty: 'No maintenance routine is available to you.', routines: 'Maintenance routines', stateFilter: 'State', allStates: 'All states', filterEmpty: 'No routine matches the filter.', state: 'State', schedule: 'Schedule', lastExecution: 'Last execution', technicalHistory: 'Technical history', administrativeAudit: 'Administrative audit', historyEmpty: 'No execution recorded.', auditEmpty: 'No administrative action recorded.', selectRoutine: 'Select a routine to view details.', backToRoutines: 'Back to routines', updateNow: 'Update now', offline: 'You are offline. Try again when the connection returns.', stale: 'Displayed data may be outdated.', loadFailed: 'We could not refresh maintenance information.', actionAccepted: 'Request accepted. Check the history for its result.', alreadyRunning: 'The routine is already running.', actionFailed: 'The request could not be completed.', synchronizationFailed: 'The official Banco Central source could not be synchronized.', synchronizationSucceeded: 'Update completed: {created} created; {updated} updated.', confirmTitle: 'Update financial institutions', confirmDescription: 'Requests an official catalog update from Banco Central. The routine may refuse the request if it is already running.', confirmAction: 'Confirm update', ibgeTerritory: { title: 'Brazilian localities', description: 'Updates the global territorial catalog with official IBGE data.', schedule: 'Automatic initial run and monthly', synchronizationFailed: 'The official IBGE source could not be synchronized.', synchronizationSucceeded: 'Territorial catalog updated.' } } });
Object.assign(en.access, { profile: { avatarRequirements: 'JPEG, PNG, or WebP, up to 10 MB and at least 400 × 400 pixels.', avatarSelectionHint: 'Choose an image or drop it in this area.', avatarSelect: 'Select image', avatarChange: 'Change image', avatarPosition: 'Image position; use arrow keys to adjust', avatarZoomValue: 'Zoom: {value}%', avatarZoomOut: 'Zoom out', avatarZoomIn: 'Zoom in', avatarCenter: 'Center', avatarSave: 'Save image', avatarFormatError: 'Choose a JPEG, PNG, or WebP image.', avatarSizeError: 'The image must be at most 10 MB.', avatarDimensionError: 'The image must be at least 400 × 400 pixels.', avatarSaveFailed: 'Unable to save the image right now.' } });
Object.assign(en.access, { profile: { section: 'Profile', description: 'Keep the identity shown across the platform up to date.', loading: 'Loading profile…', identity: 'Profile image', imageCurrent: 'Current image', noImage: 'No image set', addImage: 'Add image', changeImage: 'Change image', removeImage: 'Remove image', avatarCurrent: 'Current profile image', avatarMissing: 'No profile image set', name: 'Name', nameRequired: 'Enter a name.', save: 'Save changes', retry: 'Try again', loadFailed: 'Unable to load the profile right now.', saveFailed: 'Unable to save the name right now.', offline: 'You are offline. Reconnect and try again.', invalidName: 'The name does not meet the requirements.', removeTitle: 'Remove profile image?', removeDescription: 'The current image will be removed from your identity on the platform. This action cannot be undone.', discardTitle: 'Discard profile changes?', discardDescription: 'The name you entered has not been saved yet. Do you want to discard it and change sections?', remain: 'Stay in Profile', discard: 'Discard changes', avatarRequirements: 'JPEG, PNG, or WebP, up to 10 MB and at least 400 × 400 pixels.', avatarSelectionHint: 'Choose an image or drop it in this area.', avatarSelect: 'Select image', avatarChange: 'Change image', avatarPosition: 'Image position; use arrow keys to adjust', avatarZoomValue: 'Zoom: {value}%', avatarZoomOut: 'Zoom out', avatarZoomIn: 'Zoom in', avatarCenter: 'Center', avatarSave: 'Save image', avatarFormatError: 'Choose a JPEG, PNG, or WebP image.', avatarSizeError: 'The image must be at most 10 MB.', avatarDimensionError: 'The image must be at least 400 × 400 pixels.', avatarSaveFailed: 'Unable to save the image right now.' } });
Object.assign(en.access, { authorization: { title: 'Tenant security', section: 'Section', tabs: { roles: 'Roles', groups: 'Groups', access: 'Access', audit: 'Audit' }, createRole: 'Create role', createGroup: 'Create group', assignRole: 'Assign role', addGroupMember: 'Add group member', removeMembership: 'Remove membership', removeMembershipConfirmation: 'This removal may revoke the final administrative access. Confirm to continue.', confirm: 'Confirm removal', cancel: 'Cancel', roleKey: 'Role key', roleId: 'Role ID', groupId: 'Group ID', membershipId: 'Membership ID', displayName: 'Display name', description: 'Description', access: 'View access', userId: 'User ID', permissionKey: 'Permission key', effectiveAccess: 'View effective access', explain: 'Explain decision', membership: 'Membership', groups: 'Groups', restrictions: 'Restrictions', decision: 'Decision', allowed: 'Allowed', denied: 'Denied', notAvailable: 'Not available', audit: 'Audit', reload: 'Reload', filter: 'Filter', previousPage: 'Previous page', nextPage: 'Next page', total: '{count} events found.', loading: 'Loading data…', emptyAudit: 'No audit event was found.', occurredAt: 'Occurred at', operation: 'Operation', target: 'Target', stale: 'Displayed data may be outdated.', offline: 'You are offline. Reconnect to continue.', accessDenied: 'You do not have permission to administer this tenant security.', requestFailed: 'The request could not be completed.', lastAdministrator: 'Removal was refused because the tenant must retain at least one administrator.', roleCreated: 'Role created successfully.', groupCreated: 'Group created successfully.', roleAssigned: 'Role assigned successfully.', groupMemberAdded: 'Member added to the group.', membershipRemoved: 'Membership removed successfully.' } });
Object.assign(en.access, { drive: { personal: 'Rinos Drive Personal', work: 'Rinos Drive Work', personalWorkspace: 'Personal workspace', workWorkspace: 'Organization workspace', root: 'My files', organizationRoot: 'Organization files', refresh: 'Refresh', newFolder: 'New folder', upload: 'Upload', tree: 'Tree', closeTree: 'Close tree', trash: 'Trash', used: '{size} used in workspace', offline: 'You are offline. Changes are unavailable.', stale: 'Displayed data may be outdated.', loadFailed: 'Unable to refresh Rinos Drive right now.', locationFailed: 'Unable to load this location right now.', locationDenied: 'You no longer have access to this location.', workspaceDenied: 'Rinos Drive access is unavailable for this context.', loading: 'Loading files…', emptyFolder: 'This folder has no files or subfolders yet.', emptyTrash: 'Trash is empty.', openTree: 'Open folder tree', path: 'Current path', viewMode: 'View mode', grid: 'Grid', list: 'List', detailsView: 'Details', table: 'Table', selected: '{count} selected | {count} selected', details: 'Details', detailsPanel: 'Item details', closeDetails: 'Close details', detailsLoading: 'Loading details…', detailsFailed: 'Unable to load details right now.', detailsDenied: 'You no longer have access to this item details.', retry: 'Try again', folder: 'Folder', file: 'File', location: 'Location', size: 'Size', modified: 'Modified', access: 'Access', editable: 'Can edit', readOnly: 'Read-only', metadataAvailable: 'Safe metadata available: {count}.', itemCollection: 'Items in {name}' } });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { openSecondPanel: 'Open second pane', closeSecondPanel: 'Close second pane' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { transferTitle: 'Transfer items', transferDescription: 'Choose how to transfer {count} item(s).', transferSource: 'Source', transferDestination: 'Destination', transferMode: 'Action', copy: 'Copy' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { folderName: 'Folder name', folderNameRequired: 'Enter a folder name.', cancel: 'Cancel', createFolderDenied: 'You do not have permission to create a folder here.', createFolderFailed: 'Unable to create the folder right now. Try again.', moveToTrash: 'Move to trash', trashConfirmationTitle: 'Move items to trash?', trashConfirmationDescription: 'The {count} selected items will remain in trash until permanently cleaned up.', trashDenied: 'You do not have permission to move these items to trash.', trashFailed: 'Unable to move the items to trash right now. Try again.' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { move: 'Move', moveDestination: 'Destination', moveDenied: 'You do not have permission to move this item.', moveFailed: 'Unable to move the item right now. Try again.' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { restore: 'Restore', restoreDenied: 'You do not have permission to restore these items.', restoreFailed: 'Unable to restore the items right now.', release: 'Delete permanently', releaseTitle: 'Delete items permanently?', releaseDescription: 'The {count} selected items will be removed from this workspace permanently.', releaseDenied: 'You do not have permission to delete these items permanently.', releaseFailed: 'Unable to delete the items permanently right now.' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { clearSelection: 'Clear selection', download: 'Download', exportSelection: 'Export selection', cancelExport: 'Cancel export', exportState: 'Export {state}.', exportFailed: 'Unable to prepare the export right now.' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { cancelUpload: 'Cancel upload', uploadState: '{progress}% · {state}', uploadQueued: 'queued', uploadUploading: 'uploading', uploadComplete: 'complete', uploadFailed: 'failed', uploadCancelled: 'cancelled' });
Object.assign((en.access as unknown as { drive: Record<string, string> }).drive, { exportTitle: 'Export selection', exportDescription: 'A private ZIP archive with the {count} selected items will be prepared. The download will be available for a limited time.' });
Object.assign(en.access as unknown as Record<string, unknown>, { people: { title: 'People', organization: 'Organization: {name}', create: 'New person', search: 'Search people', status: 'Status', type: 'Type', sections: 'Person sections', basicData: 'Basic data', filters: 'Filters', closeFilters: 'Close filters', applyFilters: 'Apply filters', contacts: 'Contacts', contactsSummary: '{count} contact | {count} contacts', active: 'Active', inactive: 'Inactive', all: 'All', reload: 'Reload', loading: 'Loading people…', empty: 'No people were found.', offline: 'You are offline. Reconnect to browse people.', accessDenied: 'You do not have permission to view people in this organization.', loadFailed: 'Unable to load people.', pagination: 'People pagination', previous: 'Previous', next: 'Next' } });

Object.assign(en.access.authorization as unknown as Record<string, unknown>, {
    sharing: {
        folderSharing: 'Folder sharing · {workspace}', personalWorkspace: 'Personal workspace', tenantWorkspace: 'Organization workspace', close: 'Close sharing', workspaceResponsible: 'Workspace responsible: {name}.', loading: 'Loading sharing…', loadFailed: 'Unable to load sharing for this folder.', newShare: 'New sharing', recipient: 'Recipient', recipientFound: 'Found recipient', selectRecipient: 'Select a person', accessLevel: 'Access level', read: 'Read', edit: 'Edit', confirm: 'Confirm sharing', empty: 'This folder has no visible sharing.', direct: 'Direct access', inheritedFrom: 'Access inherited from folder #{resourceId}', change: 'Change', revoke: 'Revoke', newAccessLevel: 'New access level', confirmChange: 'Confirm change', cancel: 'Cancel', revokeQuestion: 'Revoke the selected direct access to this folder?', confirmRevoke: 'Confirm revocation', reload: 'Reload', created: 'Sharing created.', updated: 'Sharing updated.', revoked: 'Sharing revoked.', stale: 'The context changed. Reload sharing before confirming again.', conflict: 'This sharing can no longer be changed in this folder; it may be inherited or have changed.', commandFailed: 'Unable to complete the change. Refresh the data and try again.', offline: 'You are offline. Reconnect before changing sharing.',
    },
});

Object.assign(en.access.authorization as unknown as Record<string, unknown>, { contextual: { noExpiration: 'No expiration', peopleAndIdentities: 'People and identities', searchSubject: 'Search for a person or identity', emptySubjects: 'No person or identity is available in this context.', serviceIdentity: 'Service identity', person: 'Person', viewAccess: 'View access', participantPagination: 'Participant pagination', subjectCanDo: 'What can {name} do?', accessValidity: 'Access validity: {value}.', whyAccess: 'Why does this access exist?', emptySources: 'No additional access source was identified.', openSharing: 'Open sharing', effectiveCapabilities: 'Effective capabilities', emptyCapabilities: 'No effective capability is available.' } });
