import type { AccessMessages } from './types';

export const es: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Accede a tu cuenta', createTitle: 'Crear cuenta', haveAccount: 'Ya tengo una cuenta', createAccountLink: 'Crear cuenta', entryDescription: 'Crea una cuenta o elige cómo quieres iniciar sesión.',
        offline: 'No tienes conexión. Las acciones estarán disponibles cuando vuelva la red.', modeLabel: 'Modo de acceso',
        modes: { register: 'Crear cuenta', password: 'Iniciar sesión', passwordless: 'Sin contraseña' },
        fields: { email: 'Correo electrónico', password: 'Contraseña', rememberMe: 'Mantenerme conectado', code: 'Código de confirmación', displayName: 'Nombre', newPassword: 'Nueva contraseña' },
        actions: { processing: 'Procesando…', createAccount: 'Crear cuenta', enter: 'Iniciar sesión', sendAccessCode: 'Entrar sin contraseña', confirming: 'Confirmando…', confirmLink: 'Confirmar enlace', completeAccess: 'Completar acceso', resendMessage: 'Reenviar mensaje', returnToAccess: 'Volver al acceso', definePassword: 'Definir contraseña', savePassword: 'Guardar contraseña', invalidateOthers: 'Invalidar otras sesiones', endSession: 'Cerrar esta sesión', cancel: 'Cancelar', invalidateSessions: 'Invalidar sesiones' },
        confirmation: { title: 'Confirma tu correo electrónico', body: 'Introduce el código de 6 dígitos enviado en el mensaje.', validFor: 'Válido durante {time}.', remembered: 'Elegiste mantener la sesión iniciada en este navegador.' },
        security: { title: 'Seguridad de acceso', greeting: 'Hola, {name}.', passwordDefined: 'Contraseña definida.', passwordOptional: 'Puedes definir una contraseña opcional.', passwordHelp: 'Mínimo de 6 caracteres y dos categorías: minúscula, mayúscula, número o símbolo.', sessions: 'Sesiones', persistent: 'Permanecerás conectado en este navegador.', active: 'Sesión actual activa.', invalidateTitle: '¿Invalidar otras sesiones?', invalidateDescription: 'Los demás navegadores y dispositivos deberán iniciar sesión de nuevo.' },
        presentation: { visualPreferences: 'Preferencias visuales', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Oscuro', textDensity: 'Densidad del texto', spacing: 'Espaciado', componentSize: 'Tamaño de elementos', compact: 'Compacto', default: 'Predeterminado', comfortable: 'Cómodo', large: 'Amplio', selectedLanguage: 'Idioma actual: {language}' },
        feedback: { emailInvalid: 'Introduce un correo electrónico válido.', displayNameRequired: 'Introduce un nombre para mostrar.', verificationSent: 'Revisa tu correo electrónico para continuar.', codeExpired: 'Este código ha caducado. Solicita un nuevo mensaje para continuar.', accessSuccess: 'Acceso completado correctamente.', requestFailed: 'No fue posible completar esta acción.', confirmationFailed: 'No fue posible confirmar este código.', confirmationInvalid: 'Este código o enlace ya no es válido. Solicita un nuevo mensaje para continuar.', confirmationRateLimited: 'No es posible completar esta acción ahora. Espera unos minutos e inténtalo de nuevo.', passwordCriteria: 'La contraseña no cumple los requisitos: mínimo de 6 caracteres y dos categorías.', passwordRequired: 'Introduce una contraseña para continuar.', passwordSet: 'Contraseña definida.', invalidateFailed: 'No fue posible invalidar las otras sesiones.', invalidateSuccess: 'Las otras sesiones fueron invalidadas.' },
    },
};
