import type { AccessMessages } from './types';

export const fr: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Accédez à votre compte', createTitle: 'Créer un compte', haveAccount: 'J’ai déjà un compte', createAccountLink: 'Créer un compte', entryDescription: 'Créez un compte ou choisissez votre mode de connexion.',
        offline: 'Vous êtes hors ligne. Les actions seront disponibles lorsque la connexion reviendra.', modeLabel: 'Mode d’accès',
        modes: { register: 'Créer un compte', password: 'Se connecter', passwordless: 'Sans mot de passe' },
        fields: { email: 'E-mail', password: 'Mot de passe', rememberMe: 'Rester connecté', code: 'Code de confirmation', displayName: 'Nom', newPassword: 'Nouveau mot de passe' },
        actions: { processing: 'Traitement…', createAccount: 'Créer un compte', enter: 'Se connecter', sendAccessCode: 'Se connecter sans mot de passe', confirming: 'Confirmation…', confirmLink: 'Confirmer le lien', completeAccess: 'Terminer l’accès', resendMessage: 'Renvoyer le message', returnToAccess: 'Retour à l’accès', definePassword: 'Définir le mot de passe', savePassword: 'Enregistrer le mot de passe', invalidateOthers: 'Invalider les autres sessions', endSession: 'Fermer cette session', cancel: 'Annuler', invalidateSessions: 'Invalider les sessions' },
        confirmation: { title: 'Confirmez votre e-mail', body: 'Saisissez le code à 6 chiffres envoyé dans le message.', validFor: 'Valide pendant {time}.', remembered: 'Vous avez choisi de rester connecté dans ce navigateur.' },
        security: { title: 'Sécurité d’accès', greeting: 'Bonjour, {name}.', passwordDefined: 'Mot de passe défini.', passwordOptional: 'Vous pouvez définir un mot de passe facultatif.', passwordHelp: 'Au moins 6 caractères et deux catégories : minuscule, majuscule, chiffre ou symbole.', sessions: 'Sessions', persistent: 'Vous resterez connecté dans ce navigateur.', active: 'Session actuelle active.', invalidateTitle: 'Invalider les autres sessions ?', invalidateDescription: 'Les autres navigateurs et appareils devront se reconnecter.' },
        presentation: { visualPreferences: 'Préférences visuelles', language: 'Langue', theme: 'Thème', light: 'Clair', dark: 'Sombre', textDensity: 'Densité du texte', spacing: 'Espacement', componentSize: 'Taille des éléments', compact: 'Compact', default: 'Par défaut', comfortable: 'Confortable', large: 'Large', selectedLanguage: 'Langue actuelle : {language}' },
        shell: { menu: 'Menu personnel', avatar: 'Menu personnel de {name}', userSettings: 'Paramètres utilisateur', settingsUnavailable: 'Disponible prochainement', signOut: 'Se déconnecter', openNavigation: 'Ouvrir la navigation', closeNavigation: 'Fermer la navigation', navigation: 'Navigation', emptyNavigation: 'Aucune zone supplémentaire n’est disponible à cette étape.' },
        workspace: { title: 'Espace de travail', emptyTitle: 'Votre espace de travail est prêt', emptyDescription: 'Ouvrez la navigation pour accéder aux espaces qui vous sont disponibles.', navigation: { title: 'Navigation', collapse: 'Réduire la navigation', expand: 'Développer la navigation', empty: 'Aucun espace n’est disponible à cette étape.' }, surface: { unavailableTitle: 'Cette surface n’est plus disponible', unavailableDescription: 'Revenez à la navigation pour choisir un espace disponible.', readyDescription: 'Cette surface est prête à recevoir le contenu approuvé.' }, taskbar: { label: 'Surfaces ouvertes', close: 'Fermer', dirty: 'Modifications non enregistrées' }, mobile: { noSurfaces: 'Aucune surface n’est ouverte.' }, dialog: { discardTitle: 'Modifications non enregistrées', discardDescription: 'Un travail n’est pas confirmé. Voulez-vous ignorer les modifications ?', informationTitle: 'Information', informationDescription: 'Une information est disponible.', warningTitle: 'Attention', warningDescription: 'Cette action requiert votre attention.', errorTitle: 'Erreur', errorDescription: 'Impossible de terminer cette action.', confirmationTitle: 'Confirmation', confirmationDescription: 'Confirmez l’action pour continuer.', close: 'Fermer', cancel: 'Annuler', discard: 'Ignorer les modifications' }, notification: { dismiss: 'Masquer la notification', contextChanged: 'Les surfaces de l’organisation précédente ont été fermées.' } },
        tenant: { title: 'Organisations', managementTitle: 'Organisations', selectAvatar: 'Sélectionner une organisation', currentAvatar: 'Organisation actuelle : {name}', current: 'Contexte :', noneSelected: 'Aucune sélectionnée', name: 'Nom de l’organisation', nameRequired: 'Saisissez le nom de l’organisation.', nameTooLong: 'Le nom ne doit pas dépasser 120 caractères.', loading: 'Chargement des organisations…', empty: 'Vous n’appartenez à aucune organisation.', personalSpace: 'Utiliser seulement mon espace', create: 'Créer une organisation', manage: 'Gérer les organisations', more: 'Plus d’organisations', searchTitle: 'Toutes les organisations', searchPlaceholder: 'Filtrer les organisations', searchResults: 'Résultats des organisations', searchEmpty: 'Aucune organisation trouvée.', close: 'Fermer le sélecteur d’organisation', selected: 'Organisation active : {name}.', personalSelected: 'Vous utilisez seulement votre espace personnel.', creationAccepted: 'L’organisation est en cours de préparation.', createFailed: 'Impossible de créer cette organisation.', availabilityChanged: 'La disponibilité a été mise à jour.', availabilityFailed: 'Impossible de mettre à jour la disponibilité.', enable: 'Activer', disable: 'Désactiver', disableConfirmationTitle: 'Désactiver l’organisation ?', disableConfirmationDescription: 'L’organisation {name} ne pourra plus être sélectionnée avant d’être réactivée.', states: { PROVISIONING: 'Préparation', ACTIVE: 'Active', INACTIVE: 'Désactivée', FAILED: 'Indisponible' }, offline: 'Vous êtes hors ligne. Réessayez lorsque la connexion revient.', loadFailed: 'Impossible de charger les organisations.', selectFailed: 'Impossible de sélectionner cette organisation.', endFailed: 'Impossible de terminer ce contexte.' },
        feedback: { emailInvalid: 'Saisissez une adresse e-mail valide.', displayNameRequired: 'Saisissez un nom d’affichage.', verificationSent: 'Vérifiez votre e-mail pour continuer.', codeExpired: 'Ce code a expiré. Demandez un nouveau message pour continuer.', accessSuccess: 'Accès effectué avec succès.', requestFailed: 'Impossible de terminer cette action.', confirmationFailed: 'Impossible de confirmer ce code.', confirmationInvalid: 'Ce code ou ce lien n’est plus valide. Demandez un nouveau message pour continuer.', confirmationRateLimited: 'Cette action ne peut pas être terminée maintenant. Attendez quelques minutes et réessayez.', passwordCriteria: 'Le mot de passe ne respecte pas les critères : au moins 6 caractères et deux catégories.', passwordRequired: 'Saisissez un mot de passe pour continuer.', passwordSet: 'Mot de passe défini.', invalidateFailed: 'Impossible d’invalider les autres sessions.', invalidateSuccess: 'Les autres sessions ont été invalidées.' },
    },
};
