import type { AccessMessages } from './types';

export const fr: AccessMessages = {
    access: {
        brand: 'Rinos One', entryTitle: 'Accédez à votre compte', createTitle: 'Créer un compte', haveAccount: 'J’ai déjà un compte', createAccountLink: 'Créer un compte', entryDescription: 'Créez un compte ou choisissez votre mode de connexion.',
        offline: 'Vous êtes hors ligne. Les actions seront disponibles lorsque la connexion reviendra.', modeLabel: 'Mode d’accès',
        modes: { register: 'Créer un compte', password: 'Se connecter', passwordless: 'Sans mot de passe' },
        fields: { email: 'E-mail', password: 'Mot de passe', rememberMe: 'Rester connecté', code: 'Code de confirmation', displayName: 'Nom', newPassword: 'Nouveau mot de passe' },
        actions: { processing: 'Traitement…', createAccount: 'Créer un compte', enter: 'Se connecter', sendAccessCode: 'Se connecter sans mot de passe', confirming: 'Confirmation…', confirmLink: 'Confirmer le lien', completeAccess: 'Terminer l’accès', resendMessage: 'Renvoyer le message', returnToAccess: 'Retour à l’accès', definePassword: 'Définir le mot de passe', savePassword: 'Enregistrer le mot de passe', invalidateOthers: 'Invalider les autres sessions', endSession: 'Fermer cette session', cancel: 'Annuler', invalidateSessions: 'Invalider les sessions' },
        confirmation: { title: 'Confirmez votre e-mail', body: 'Saisissez le code à 6 chiffres envoyé dans le message.', validFor: 'Valide pendant {time}.', remembered: 'Vous avez choisi de rester connecté dans ce navigateur.' },
        security: { title: 'Sécurité d’accès', greeting: 'Bonjour, {name}.', passwordDefined: 'Mot de passe défini.', passwordOptional: 'Vous pouvez définir un mot de passe facultatif.', passwordHelp: 'Au moins 6 caractères et deux catégories : minuscule, majuscule, chiffre ou symbole.', sessions: 'Sessions', persistent: 'Vous resterez connecté dans ce navigateur.', active: 'Session actuelle active.', invalidateTitle: 'Invalider les autres sessions ?', invalidateDescription: 'Les autres navigateurs et appareils devront se reconnecter.' },
        presentation: { visualPreferences: 'Préférences visuelles', language: 'Langue', theme: 'Thème', light: 'Clair', dark: 'Sombre', textDensity: 'Densité du texte', spacing: 'Espacement', componentSize: 'Taille des éléments', compact: 'Compact', default: 'Par défaut', comfortable: 'Confortable', large: 'Large', selectedLanguage: 'Langue actuelle : {language}' },
        feedback: { emailInvalid: 'Saisissez une adresse e-mail valide.', displayNameRequired: 'Saisissez un nom d’affichage.', verificationSent: 'Vérifiez votre e-mail pour continuer.', codeExpired: 'Ce code a expiré. Demandez un nouveau message pour continuer.', accessSuccess: 'Accès effectué avec succès.', requestFailed: 'Impossible de terminer cette action.', confirmationFailed: 'Impossible de confirmer ce code.', confirmationInvalid: 'Ce code ou ce lien n’est plus valide. Demandez un nouveau message pour continuer.', confirmationRateLimited: 'Cette action ne peut pas être terminée maintenant. Attendez quelques minutes et réessayez.', passwordCriteria: 'Le mot de passe ne respecte pas les critères : au moins 6 caractères et deux catégories.', passwordRequired: 'Saisissez un mot de passe pour continuer.', passwordSet: 'Mot de passe défini.', invalidateFailed: 'Impossible d’invalider les autres sessions.', invalidateSuccess: 'Les autres sessions ont été invalidées.' },
    },
};
