export const ptBR = {
    access: {
        brand: 'Rinos One',
        entryTitle: 'Acesse sua conta', createTitle: 'Criar conta', haveAccount: 'Já tenho uma conta', createAccountLink: 'Criar conta',
        entryDescription: 'Crie uma conta ou escolha como deseja entrar.',
        offline: 'Você está sem conexão. As ações estarão disponíveis quando a rede voltar.',
        modeLabel: 'Modo de acesso',
        modes: { register: 'Criar conta', password: 'Entrar', passwordless: 'Sem senha' },
        fields: {
            email: 'E-mail', password: 'Senha', rememberMe: 'Manter-me conectado', code: 'Código de confirmação',
            displayName: 'Nome', newPassword: 'Nova senha',
        },
        actions: {
            processing: 'Processando…', createAccount: 'Criar conta', enter: 'Entrar', sendAccessCode: 'Entrar sem senha',
            confirming: 'Confirmando…', confirmLink: 'Confirmar link', completeAccess: 'Concluir acesso', resendMessage: 'Reenviar mensagem', resendMessageIn: 'Reenviar em {time}',
            returnToAccess: 'Voltar ao acesso', definePassword: 'Definir senha', savePassword: 'Salvar senha',
            invalidateOthers: 'Invalidar outras sessões', endSession: 'Encerrar esta sessão', cancel: 'Cancelar', invalidateSessions: 'Invalidar sessões',
        },
        confirmation: {
            title: 'Confirme seu e-mail', body: 'Digite o código de 6 dígitos enviado na mensagem.', validFor: 'Válido por {time}.',
            remembered: 'Você escolheu permanecer conectado neste navegador.',
        },
        security: {
            title: 'Segurança de acesso', greeting: 'Olá, {name}.', passwordDefined: 'Senha definida.',
            passwordOptional: 'Você pode definir uma senha opcional.', passwordHelp: 'Mínimo de 6 caracteres e duas categorias: minúscula, maiúscula, número ou símbolo.',
            sessions: 'Sessões', persistent: 'Você permanecerá conectado neste navegador.', active: 'Sessão atual ativa.',
            invalidateTitle: 'Invalidar outras sessões?', invalidateDescription: 'Os outros navegadores e dispositivos precisarão entrar novamente.',
        },
        presentation: {
            visualPreferences: 'Preferências visuais', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Escuro',
            textDensity: 'Densidade do texto', spacing: 'Espaçamento', componentSize: 'Tamanho dos elementos',
            compact: 'Compacto', default: 'Padrão', comfortable: 'Confortável', large: 'Amplo', selectedLanguage: 'Idioma atual: {language}',
        },
        shell: { menu: 'Menu pessoal', avatar: 'Menu pessoal de {name}', userSettings: 'Configurações do usuário', settingsUnavailable: 'Disponível em breve', signOut: 'Sair', openNavigation: 'Abrir navegação', closeNavigation: 'Fechar navegação', navigation: 'Navegação', emptyNavigation: 'Nenhuma área adicional está disponível nesta fase.' },
        workspace: { title: 'Área de trabalho', emptyTitle: 'Sua área de trabalho está pronta', emptyDescription: 'Abra a navegação para acessar as áreas disponíveis para você.', navigation: { title: 'Navegação', collapse: 'Recolher navegação', expand: 'Expandir navegação', empty: 'Nenhuma área está disponível nesta etapa.' }, surface: { unavailableTitle: 'Esta superfície não está mais disponível', unavailableDescription: 'Retorne à navegação para escolher uma área disponível.', readyDescription: 'Esta superfície está pronta para receber o conteúdo aprovado.' }, taskbar: { label: 'Superfícies abertas', close: 'Fechar', dirty: 'Alterações não salvas' }, mobile: { noSurfaces: 'Nenhuma superfície está aberta.' }, dialog: { discardTitle: 'Alterações não salvas', discardDescription: 'Há trabalho não confirmado. Deseja descartar as alterações?', informationTitle: 'Informação', informationDescription: 'Há uma informação disponível.', warningTitle: 'Atenção', warningDescription: 'Esta ação exige sua atenção.', errorTitle: 'Erro', errorDescription: 'Não foi possível concluir esta ação.', confirmationTitle: 'Confirmação', confirmationDescription: 'Confirme a ação para continuar.', close: 'Fechar', cancel: 'Cancelar', discard: 'Descartar alterações' }, notification: { dismiss: 'Dispensar notificação', contextChanged: 'As superfícies da organização anterior foram fechadas.' } },
        maintenance: { eyebrow: 'Administração da Plataforma', title: 'Central de Manutenções', reload: 'Recarregar', loading: 'Carregando rotinas…', empty: 'Nenhuma rotina de manutenção está disponível para seu acesso.', routines: 'Rotinas de manutenção', stateFilter: 'Estado', allStates: 'Todos os estados', filterEmpty: 'Nenhuma rotina corresponde ao filtro.', state: 'Estado', schedule: 'Agenda', lastExecution: 'Última execução', technicalHistory: 'Histórico técnico', administrativeAudit: 'Auditoria administrativa', historyEmpty: 'Nenhuma execução registrada.', auditEmpty: 'Nenhuma ação administrativa registrada.', selectRoutine: 'Selecione uma rotina para consultar os detalhes.', backToRoutines: 'Voltar às rotinas', updateNow: 'Atualizar agora', offline: 'Você está sem conexão. Tente novamente quando a rede voltar.', stale: 'Os dados exibidos podem estar desatualizados.', loadFailed: 'Não foi possível atualizar as informações de manutenção.', actionAccepted: 'Solicitação aceita. Consulte o histórico para acompanhar o resultado.', alreadyRunning: 'A rotina já está em execução.', actionFailed: 'A solicitação não pôde ser concluída.', synchronizationFailed: 'Não foi possível sincronizar a fonte oficial do Banco Central.', synchronizationSucceeded: 'Atualização concluída: {created} criadas; {updated} atualizadas.', confirmTitle: 'Atualizar instituições financeiras', confirmDescription: 'Solicita uma atualização do catálogo oficial pelo Banco Central. A rotina pode recusar a solicitação caso já esteja em execução.', confirmAction: 'Confirmar atualização' },
        authorization: { title: 'Segurança do tenant', section: 'Seção', tabs: { roles: 'Roles', groups: 'Grupos', access: 'Acessos', audit: 'Auditoria' }, createRole: 'Criar role', createGroup: 'Criar grupo', assignRole: 'Atribuir role', addGroupMember: 'Adicionar membro ao grupo', removeMembership: 'Remover membership', removeMembershipConfirmation: 'Esta remoção pode revogar o último acesso administrativo. Confirme para continuar.', confirm: 'Confirmar remoção', cancel: 'Cancelar', roleKey: 'Chave da role', roleId: 'ID da role', groupId: 'ID do grupo', membershipId: 'ID da membership', displayName: 'Nome de exibição', description: 'Descrição', access: 'Consultar acesso', userId: 'ID do usuário', permissionKey: 'Chave da permission', effectiveAccess: 'Consultar acesso efetivo', explain: 'Explicar decisão', membership: 'Membership', groups: 'Grupos', restrictions: 'Restrictions', decision: 'Decisão', allowed: 'Permitida', denied: 'Negada', notAvailable: 'Não disponível', audit: 'Auditoria', reload: 'Recarregar', filter: 'Filtrar', previousPage: 'Página anterior', nextPage: 'Próxima página', total: '{count} eventos encontrados.', loading: 'Carregando dados…', emptyAudit: 'Nenhum evento de auditoria foi encontrado.', occurredAt: 'Ocorrido em', operation: 'Operação', target: 'Alvo', stale: 'Os dados exibidos podem estar desatualizados.', offline: 'Você está sem conexão. Reconecte-se para continuar.', accessDenied: 'Você não tem permissão para administrar a segurança deste tenant.', requestFailed: 'Não foi possível concluir a solicitação.', lastAdministrator: 'A remoção foi recusada porque o tenant precisa manter ao menos um administrador.', roleCreated: 'Role criada com sucesso.', groupCreated: 'Grupo criado com sucesso.', roleAssigned: 'Role atribuída com sucesso.', groupMemberAdded: 'Membro adicionado ao grupo.', membershipRemoved: 'Membership removida com sucesso.' },
        tenant: { title: 'Organizações', managementTitle: 'Organizações', selectAvatar: 'Selecionar organização', currentAvatar: 'Organização atual: {name}', current: 'Contexto:', noneSelected: 'Nenhuma selecionada', name: 'Nome da organização', nameRequired: 'Informe o nome da organização.', nameTooLong: 'O nome deve ter no máximo 120 caracteres.', loading: 'Carregando organizações…', empty: 'Você não pertence a nenhuma organização.', personalSpace: 'Usar somente meu espaço', create: 'Criar organização', manage: 'Gerenciar organizações', more: 'Mais organizações', searchTitle: 'Todas as organizações', searchPlaceholder: 'Filtrar organizações', searchResults: 'Resultados de organizações', searchEmpty: 'Nenhuma organização encontrada.', close: 'Fechar seletor de organização', selected: 'Organização ativa: {name}.', personalSelected: 'Você está usando somente seu espaço.', creationAccepted: 'A organização está sendo preparada.', createFailed: 'Não foi possível criar esta organização.', availabilityChanged: 'A disponibilidade foi atualizada.', availabilityFailed: 'Não foi possível atualizar a disponibilidade.', enable: 'Habilitar', disable: 'Desabilitar', disableConfirmationTitle: 'Desabilitar organização?', disableConfirmationDescription: 'A organização {name} não poderá ser selecionada até ser habilitada novamente.', states: { PROVISIONING: 'Preparando', ACTIVE: 'Ativa', INACTIVE: 'Desabilitada', FAILED: 'Indisponível' }, offline: 'Você está sem conexão. Tente novamente quando a rede voltar.', loadFailed: 'Não foi possível carregar as organizações.', selectFailed: 'Não foi possível selecionar esta organização.', endFailed: 'Não foi possível encerrar este contexto.' },
        profile: { section: 'Perfil', description: 'Mantenha a identidade exibida na plataforma.', loading: 'Carregando perfil…', identity: 'Imagem de perfil', imageCurrent: 'Imagem atual', noImage: 'Nenhuma imagem definida', addImage: 'Adicionar imagem', changeImage: 'Alterar imagem', removeImage: 'Remover imagem', avatarCurrent: 'Imagem de perfil atual', avatarMissing: 'Imagem de perfil não definida', name: 'Nome', nameRequired: 'Informe um nome.', save: 'Salvar alterações', retry: 'Tentar novamente', loadFailed: 'Não foi possível carregar o perfil agora.', saveFailed: 'Não foi possível salvar o nome agora.', offline: 'Você está sem conexão. Reconecte-se e tente novamente.', invalidName: 'O nome informado não atende aos requisitos.', removeTitle: 'Remover imagem de perfil?', removeDescription: 'A imagem atual será removida da sua identidade na plataforma. Esta ação não pode ser desfeita.', discardTitle: 'Descartar alterações no perfil?', discardDescription: 'O nome que você digitou ainda não foi salvo. Deseja descartá-lo e mudar de seção?', remain: 'Permanecer em Perfil', discard: 'Descartar alterações' },
        feedback: {
            emailInvalid: 'Informe um e-mail válido.', displayNameRequired: 'Informe um nome de exibição.', verificationSent: 'Verifique seu e-mail para continuar.', passwordlessRequestAccepted: 'Se existir uma conta para {email}, enviaremos um e-mail de acesso sem senha.', resendCooldown: 'Aguarde {time} para solicitar uma nova mensagem.', codeExpired: 'Este código expirou. Solicite uma nova mensagem para continuar.',
            accessSuccess: 'Acesso concluído com sucesso.', requestFailed: 'Não foi possível concluir esta ação.',
            confirmationFailed: 'Não foi possível confirmar este código.', confirmationInvalid: 'Este código ou link não é mais válido. Solicite uma nova mensagem para continuar.',
            confirmationRateLimited: 'Não é possível concluir esta ação agora. Aguarde alguns minutos e tente novamente.',
            passwordCriteria: 'A senha não atende aos critérios: mínimo de 6 caracteres e duas categorias.', passwordRequired: 'Informe uma senha para continuar.', passwordSet: 'Senha definida.',
            invalidateFailed: 'Não foi possível invalidar as outras sessões.', invalidateSuccess: 'Outras sessões foram invalidadas.',
        },
    },
} as const;
