import { flushPromises, mount } from '@vue/test-utils';
import axios from 'axios';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import PeopleCatalog from '../../../resources/js/people/PeopleCatalog.vue';
import { i18n } from '../../../resources/js/i18n';

vi.mock('axios');
const response = { people: [{ id: 1, displayName: 'Ana', personType: 'PF', document: '123', status: 'ACTIVE', contactCount: 0, outsideSearch: false }], range: { offset: 0, limit: 100, total: 1 }, matchedTotal: 1, hiddenSelectedTotal: 0 };
function mountCatalog(options: { attachTo?: Element } = {}) { return mount(PeopleCatalog, { ...options, props: { surface: { id: 'people', destinationId: 'tenant.people', scope: 'tenant', tenantId: 18, titleKey: 'access.people.title', icon: 'personCompany', dirty: false, status: 'active' }, capabilities: { canCreatePeople: true, canUpdatePeople: true } }, global: { plugins: [i18n], stubs: { UiDialog: { template: '<div><slot /></div>' } } } }); }
describe('PeopleCatalog', () => {
    beforeEach(() => { vi.resetAllMocks(); vi.mocked(axios.post).mockResolvedValue({ data: response }); });
    it('loads the first lazy range and keeps a permanent status bar', async () => { const wrapper = mountCatalog(); await flushPromises(); expect(axios.post).toHaveBeenCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ offset: 0, limit: 100 })); expect(wrapper.get('.people-catalog__status').text()).toContain('1 Pessoa encontrada.'); });
    it('uses integrated search without pagination', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('input[type="search"]').setValue('Ana'); await wrapper.get('.people-catalog__search button').trigger('click'); expect(wrapper.find('.people-catalog__pagination').exists()).toBe(false); });
    it('keeps the insert action secondary and groups the filter with the search', async () => { const wrapper = mountCatalog(); await flushPromises(); const toolbar = wrapper.get('.people-catalog__toolbar'); const searchTools = wrapper.get('.people-catalog__search-tools'); expect(toolbar.element.firstElementChild).toBe(searchTools.element); expect(searchTools.get('.people-catalog__search').element).toBeInstanceOf(HTMLElement); expect(searchTools.get('.people-catalog__filter-trigger img').attributes('src')).toContain('funnel_24.png'); const insert = wrapper.findAll('.people-catalog__actions button').find((button) => button.text().includes('Inserir'))!; expect(insert.classes()).toContain('ui-button--secondary'); expect(insert.classes()).not.toContain('ui-button--primary'); });
    it('explains why a single-record action cannot run without a selection', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.findAll('.people-catalog__actions button').find((button) => button.text().includes('Editar'))!.trigger('click'); expect(wrapper.text()).toContain('selecione somente um registro'); });
    it('opens the clicked record with double click without altering selection', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('tbody tr').trigger('dblclick'); expect(wrapper.emitted('action')?.[0]?.slice(0, 2)).toEqual([1, 'view']); });
    it('resolves every result ID when select all is requested', async () => { vi.mocked(axios.post).mockResolvedValueOnce({ data: response }).mockResolvedValueOnce({ data: { ids: [1, 2], total: 2, exceedsLimit: false } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('thead input[type="checkbox"]').trigger('change'); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/selection-ids', expect.any(Object)); });
    it('keeps explicit IDs when showing selected records lazily', async () => { vi.mocked(axios.post).mockResolvedValueOnce({ data: response }).mockResolvedValueOnce({ data: { ids: [1, 2], total: 2, exceedsLimit: false } }).mockResolvedValueOnce({ data: { ...response, range: { ...response.range, total: 2 } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('thead input[type="checkbox"]').trigger('change'); await wrapper.findAll('.people-catalog__toolbar-actions .ui-icon-button')[1].trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ includeIds: [1, 2], selectedIds: [1, 2], selectedOnly: true })); });
    it('shows direction and priority while sending up to three server-side sorting criteria', async () => { const wrapper = mountCatalog(); await flushPromises(); const headers = wrapper.findAll('.people-catalog__sort-trigger'); await headers[1].trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ sorts: [{ column: 'personType', direction: 'asc' }] })); await headers[2].trigger('click', { shiftKey: true }); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ sorts: [{ column: 'document', direction: 'asc' }, { column: 'personType', direction: 'asc' }] })); expect(wrapper.findAll('.people-catalog__sort-priority').map((item) => item.text())).toEqual(['2', '1']); });
    it('keeps the columns popover focused on visibility toggles', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__toolbar-actions button:last-child').trigger('click'); expect(wrapper.findAll('.people-catalog__column-toggle')).toHaveLength(4); expect(wrapper.find('.people-catalog__columns input').exists()).toBe(false); expect(wrapper.find('.people-catalog__columns input[type="number"]').exists()).toBe(false); });
    it('uses icon-only table tools with accessible descriptive tooltips', async () => { const wrapper = mountCatalog(); await flushPromises(); const tools = wrapper.findAll('.people-catalog__toolbar-actions .ui-icon-button'); expect(tools).toHaveLength(5); expect(tools.map((tool) => tool.text())).toEqual(['', '', '', '', '']); expect(tools.map((tool) => tool.attributes('title'))).toEqual(['Manter seleção entre buscas — preserva os itens selecionados ao realizar uma nova busca.', 'Exibir selecionados — limita a tabela aos itens atualmente selecionados.', 'Incluir selecionados ocultos — também mostra os selecionados que não correspondem à busca atual.', 'Limpar seleção', 'Colunas']); });
    it('closes the columns popover only when interaction occurs outside it', async () => { const wrapper = mountCatalog({ attachTo: document.body }); await flushPromises(); await wrapper.get('.people-catalog__toolbar-actions button:last-child').trigger('click'); await wrapper.get('.people-catalog__column-toggle').trigger('click'); expect(wrapper.find('.people-catalog__columns').exists()).toBe(true); document.body.dispatchEvent(new Event('pointerdown', { bubbles: true })); await wrapper.vm.$nextTick(); expect(wrapper.find('.people-catalog__columns').exists()).toBe(false); wrapper.unmount(); });
    it('loads the backend filter schema before opening the reusable advanced filter', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [{ key: 'bankAccounts', label: 'Dados bancários' }], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); expect(axios.get).toHaveBeenCalledWith('/api/v1/tenants/18/people/filter-schema'); expect(wrapper.find('.advanced-filter-builder').exists()).toBe(true); });
});
