import { flushPromises, mount } from '@vue/test-utils';
import axios from 'axios';
import { createPinia, setActivePinia } from 'pinia';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import PeopleCatalog from '../../../resources/js/people/PeopleCatalog.vue';
import { i18n } from '../../../resources/js/i18n';

vi.mock('axios');
const response = { people: [{ id: 1, displayName: 'Ana', personType: 'PF', document: '123', status: 'ACTIVE', contactCount: 0, outsideSearch: false }], range: { offset: 0, limit: 100, total: 1 }, matchedTotal: 1, hiddenSelectedTotal: 0 };
function mountCatalog(options: { attachTo?: Element; stubDialogs?: boolean } = {}) { const { stubDialogs = true, ...mountOptions } = options; const pinia = createPinia(); setActivePinia(pinia); return mount(PeopleCatalog, { ...mountOptions, props: { surface: { id: 'people', destinationId: 'tenant.people', scope: 'tenant', tenantId: 18, titleKey: 'access.people.title', icon: 'personCompany', dirty: false, status: 'active' }, capabilities: { canCreatePeople: true, canUpdatePeople: true } }, global: { plugins: [i18n, pinia], stubs: stubDialogs ? { UiDialog: { template: '<div><slot /></div>' } } : {} } }); }
describe('PeopleCatalog', () => {
    beforeEach(() => { vi.resetAllMocks(); vi.mocked(axios.post).mockResolvedValue({ data: response }); });
    it('loads the first lazy range and keeps a permanent status bar', async () => { const wrapper = mountCatalog(); await flushPromises(); expect(axios.post).toHaveBeenCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ offset: 0, limit: 100 })); expect(wrapper.get('.people-catalog__status').text()).toContain('1 Pessoa encontrada.'); });
    it('uses integrated search without pagination', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('input[type="search"]').setValue('Ana'); await wrapper.get('.people-catalog__search-tools [aria-label="Pesquisar"]').trigger('click'); expect(wrapper.find('.people-catalog__pagination').exists()).toBe(false); });
    it('uses centralized groups and canonical commands for search and record actions', async () => { const wrapper = mountCatalog(); await flushPromises(); const toolbar = wrapper.get('.people-catalog__toolbar'); const searchTools = wrapper.get('.people-catalog__search-tools'); expect(toolbar.element.firstElementChild).toBe(searchTools.element); expect(searchTools.attributes('role')).toBe('group'); expect(searchTools.get('.people-catalog__search').element).toBeInstanceOf(HTMLElement); expect(searchTools.get('.people-catalog__filter-trigger img').attributes('src')).toContain('funnel_48.png'); const actions = wrapper.get('.people-catalog__actions'); expect(actions.attributes('role')).toBe('group'); const insert = actions.findAll('button').find((button) => button.text().includes('Inserir'))!; expect(insert.classes()).toContain('ui-button--secondary'); expect(insert.classes()).not.toContain('ui-button--primary'); expect(insert.get('img').attributes('src')).toContain('dataInsert_48.png'); });
    it('explains why a single-record action cannot run without a selection', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.findAll('.people-catalog__actions button').find((button) => button.text().includes('Alterar'))!.trigger('click'); expect(wrapper.text()).toContain('selecione somente um registro'); });
    it('opens the clicked record with double click without altering selection', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('tbody tr').trigger('dblclick'); expect(wrapper.emitted('action')?.[0]?.slice(0, 2)).toEqual([1, 'view']); });
    it('resolves every result ID when select all is requested', async () => { vi.mocked(axios.post).mockResolvedValueOnce({ data: response }).mockResolvedValueOnce({ data: { ids: [1, 2], total: 2, exceedsLimit: false } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('thead input[type="checkbox"]').trigger('change'); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/selection-ids', expect.any(Object)); });
    it('keeps explicit IDs when showing selected records lazily', async () => { vi.mocked(axios.post).mockResolvedValueOnce({ data: response }).mockResolvedValueOnce({ data: { ids: [1, 2], total: 2, exceedsLimit: false } }).mockResolvedValueOnce({ data: { ...response, range: { ...response.range, total: 2 } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('thead input[type="checkbox"]').trigger('change'); await wrapper.findAll('.people-catalog__toolbar-actions .ui-icon-button')[1].trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ includeIds: [1, 2], selectedIds: [1, 2], selectedOnly: true })); });
    it('shows direction and priority while sending up to three server-side sorting criteria', async () => { const wrapper = mountCatalog(); await flushPromises(); const headers = wrapper.findAll('.people-catalog__sort-trigger'); await headers[1].trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ sorts: [{ column: 'personType', direction: 'asc' }] })); await headers[2].trigger('click', { shiftKey: true }); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ sorts: [{ column: 'document', direction: 'asc' }, { column: 'personType', direction: 'asc' }] })); expect(wrapper.findAll('.people-catalog__sort-priority').map((item) => item.text())).toEqual(['2', '1']); });
    it('keeps the columns popover focused on visibility toggles', async () => { const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('[aria-label="Colunas"]').trigger('click'); expect(wrapper.findAll('.people-catalog__column-toggle')).toHaveLength(4); expect(wrapper.find('.people-catalog__columns input').exists()).toBe(false); expect(wrapper.find('.people-catalog__columns input[type="number"]').exists()).toBe(false); });
    it('uses centralized icon-only table tools with their mandatory accessible names', async () => { const wrapper = mountCatalog(); await flushPromises(); const tools = wrapper.findAll('.people-catalog__toolbar-actions .ui-icon-button'); expect(tools).toHaveLength(5); expect(tools.map((tool) => tool.text())).toEqual(['', '', '', '', '']); expect(tools.map((tool) => tool.attributes('title'))).toEqual(['Manter seleção', 'Exibir selecionados', 'Incluir selecionados ocultos', 'Limpar seleção', 'Colunas']); });
    it('closes the columns popover only when interaction occurs outside it', async () => { const wrapper = mountCatalog({ attachTo: document.body }); await flushPromises(); await wrapper.get('[aria-label="Colunas"]').trigger('click'); await wrapper.get('.people-catalog__column-toggle').trigger('click'); expect(wrapper.find('.people-catalog__columns').exists()).toBe(true); document.body.dispatchEvent(new Event('pointerdown', { bubbles: true })); await wrapper.vm.$nextTick(); expect(wrapper.find('.people-catalog__columns').exists()).toBe(false); wrapper.unmount(); });
    it('loads the backend filter schema before opening the reusable advanced filter', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [{ key: 'bankAccounts', label: 'Dados bancários' }], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); expect(axios.get).toHaveBeenCalledWith('/api/v1/tenants/18/people/filter-schema'); expect(wrapper.find('.advanced-filter-builder').exists()).toBe(true); });
    it('recreates the value editor when the chosen field changes its type', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [{ key: 'bankAccounts', label: 'Dados bancários' }], fields: [{ key: 'cpf', label: 'CPF/CNPJ', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }, { key: 'bankAccounts.status', label: 'Dados bancários › Situação', type: 'ENUM', relation: 'bankAccounts', operators: ['EQUALS'], options: [{ value: 'ACTIVE', label: 'Ativa' }] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); const condition = wrapper.get('.advanced-filter-condition'); await condition.findAll('select')[0]!.setValue('bankAccounts.status'); await wrapper.vm.$nextTick(); expect(condition.find('.advanced-filter-condition__value select').exists()).toBe(true); await condition.findAll('select')[0]!.setValue('cpf'); await wrapper.vm.$nextTick(); expect(condition.find('.advanced-filter-condition__value input[type="text"]').exists()).toBe(true); });
    it('selects multiple enumeration values by clicking their options without modifier keys', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }, { key: 'status', label: 'Situação', type: 'ENUM', relation: null, operators: ['IN'], options: [{ value: 'ACTIVE', label: 'Ativa' }, { value: 'INACTIVE', label: 'Inativa' }] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); const condition = wrapper.get('.advanced-filter-condition'); await condition.findAll('select')[0]!.setValue('status'); await wrapper.vm.$nextTick(); await condition.findAll('select')[1]!.setValue('IN'); await wrapper.vm.$nextTick(); await condition.get('.ui-multi-select__trigger').trigger('click'); const options = condition.findAll('.ui-multi-select__option'); await options[0]!.trigger('click'); await options[1]!.trigger('click'); expect(condition.findAll('.ui-multi-select__option--selected')).toHaveLength(2); });
    it('applies a valid advanced filter by reloading the list with its tree', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); await wrapper.findAll('.people-catalog__filter-dialog-actions .ui-button--primary').find((button) => button.text() === 'Aplicar filtro')!.trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ advancedFilter: expect.objectContaining({ kind: 'group', children: [expect.objectContaining({ field: 'displayName', operator: 'CONTAINS' })] }), search: undefined })); });
    it('marks an active advanced filter and confirms before a simple search replaces it', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog({ attachTo: document.body, stubDialogs: false }); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); await wrapper.findAll('.people-catalog__filter-dialog-actions .ui-button--primary').find((button) => button.text() === 'Aplicar filtro')!.trigger('click'); await flushPromises(); expect(wrapper.get('.people-catalog__filter-trigger').attributes('aria-pressed')).toBe('true'); await wrapper.get('input[type="search"]').setValue('Ana'); await wrapper.get('input[type="search"]').trigger('keydown', { key: 'Enter' }); await wrapper.vm.$nextTick(); expect(wrapper.find('[aria-label="Substituir filtro avançado?"]').exists()).toBe(true); await wrapper.get('[aria-label="Substituir filtro avançado?"]').findAll('button').find((button) => button.text() === 'Remover filtro e buscar')!.trigger('click'); await flushPromises(); expect(axios.post).toHaveBeenLastCalledWith('/api/v1/tenants/18/people/query', expect.objectContaining({ advancedFilter: undefined, search: 'Ana' })); wrapper.unmount(); });
    it('opens the filter dialog and its builder in the current window context', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog({ attachTo: document.body, stubDialogs: false }); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); expect(wrapper.find('.ui-dialog-backdrop').exists()).toBe(true); expect(wrapper.find('.advanced-filter-builder').exists()).toBe(true); expect(wrapper.find('[aria-label="Adicionar condição"]').exists()).toBe(true); wrapper.unmount(); });
    it('updates the filter tree through condition, group and match-mode commands', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [{ key: 'bankAccounts', label: 'Dados bancários' }], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS', 'IS_EMPTY'], options: [] }, { key: 'bankAccounts.label', label: 'Dados bancários › Identificação', type: 'TEXT', relation: 'bankAccounts', operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); const conditionAdd = wrapper.get('[aria-label="Adicionar condição"]'); await conditionAdd.trigger('click'); expect(wrapper.findAll('.advanced-filter-condition')).toHaveLength(2); const firstCondition = wrapper.findAll('.advanced-filter-condition')[0]!; await firstCondition.findAll('select')[1]!.setValue('IS_EMPTY'); expect(firstCondition.find('input[type="text"]').exists()).toBe(false); await wrapper.get('[aria-label="Adicionar grupo"]').trigger('click'); expect(wrapper.findAll('.advanced-filter-group')).toHaveLength(2); const rootMatchMode = wrapper.findAll('.advanced-filter-group__header select')[0]!; await rootMatchMode.setValue('SAME_RECORD'); expect(wrapper.findAll('.advanced-filter-group__header select')).toHaveLength(2); await wrapper.get('[aria-label="Remover condição"]').trigger('click'); expect(wrapper.findAll('.advanced-filter-condition')).toHaveLength(2); expect(wrapper.get('[aria-label="Remover condição"] img').attributes('src')).toContain('fileDelete_48.png'); });
    it('moves a condition through the drag handle without losing its definition', async () => { vi.mocked(axios.get).mockResolvedValue({ data: { filterSchema: { maximumDepth: 5, maximumConditions: 50, relations: [], fields: [{ key: 'displayName', label: 'Nome de exibição', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }, { key: 'name', label: 'Nome', type: 'TEXT', relation: null, operators: ['CONTAINS'], options: [] }] } } }); const wrapper = mountCatalog(); await flushPromises(); await wrapper.get('.people-catalog__filter-trigger').trigger('click'); await flushPromises(); await wrapper.get('[aria-label="Adicionar condição"]').trigger('click'); const conditions = wrapper.findAll('.advanced-filter-condition'); await conditions[1]!.find('select').setValue('name'); let draggedId = ''; const transfer = { effectAllowed: '', setData: (_type: string, value: string) => { draggedId = value; }, getData: () => draggedId }; await conditions[1]!.get('[aria-label="Arrastar condição"]').trigger('dragstart', { dataTransfer: transfer }); await conditions[0]!.trigger('drop', { dataTransfer: transfer, clientY: -1 }); expect(wrapper.findAll('.advanced-filter-condition')[0]!.find('select').element.value).toBe('name'); });
});
