<script setup lang="ts">
import axios from 'axios';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import UiAlert from '../design-system/UiAlert.vue';
import UiButton from '../design-system/UiButton.vue';
import { parseAuthorizedFolders, type AuthorizedFolder as Folder } from './authorizedFoldersApi';

const folders = ref<Folder[]>([]); const selected = ref<Folder | null>(null); const loading = ref(true); const processing = ref(false); const error = ref(''); const offline = ref(!navigator.onLine); const stale = ref(false);
const hasData = computed(() => folders.value.length > 0);
function online() { offline.value = false; } function offlineNow() { offline.value = true; }
async function reload(): Promise<void> { loading.value = true; error.value = ''; if (offline.value) { error.value = 'Você está offline.'; stale.value = hasData.value; loading.value = false; return; } try { const response = await axios.get('/api/v1/authorization/personal-workspace/folders'); const parsed = parseAuthorizedFolders(response.data); if (parsed === null) throw new Error('Invalid response'); folders.value = parsed; stale.value = false; } catch { stale.value = hasData.value; error.value = 'Não foi possível carregar os arquivos acessíveis.'; } finally { loading.value = false; } }
async function openFolder(folder: Folder): Promise<void> { if (offline.value) return; processing.value = true; error.value = ''; try { const response = await axios.post('/api/v1/authorization/resource-checks', { checks: [{ permissionKey: 'personal.folder.read', resource: { type: 'personal.folder', id: folder.id } }] }); if (response.data?.decisions?.[0]?.allowed !== true) { folders.value = folders.value.filter((item) => item.id !== folder.id); selected.value = null; return; } selected.value = folder; } catch { error.value = 'Não foi possível abrir esta pasta.'; } finally { processing.value = false; } }
onMounted(() => { window.addEventListener('online', online); window.addEventListener('offline', offlineNow); void reload(); }); onBeforeUnmount(() => { window.removeEventListener('online', online); window.removeEventListener('offline', offlineNow); });
</script>
<template><main class="workspace-folders" aria-labelledby="workspace-folders-title"><header><div><p>Workspace pessoal</p><h2 id="workspace-folders-title" tabindex="-1">Arquivos e anexos</h2></div><UiButton variant="secondary" :loading="loading" :disabled="offline" @click="reload">Atualizar</UiButton></header><div aria-live="polite"><UiAlert v-if="offline" tone="warning">Você está offline.</UiAlert><UiAlert v-if="stale" tone="warning">Os dados exibidos podem estar desatualizados.</UiAlert><UiAlert v-if="error" tone="error">{{ error }}</UiAlert></div><p v-if="selected">Pasta aberta: <strong>{{ selected.displayName }}</strong></p><p v-if="loading && !hasData" aria-live="polite">Carregando arquivos acessíveis…</p><p v-else-if="!loading && !folders.length">Não há pastas acessíveis.</p><nav v-else aria-label="Pastas acessíveis"><button v-for="folder in folders" :key="folder.id" type="button" :disabled="processing" @click="openFolder(folder)"><strong>{{ folder.displayName }}</strong><span v-if="folder.parentFolderId !== null">Pasta compartilhada</span></button></nav></main></template>
<style scoped>.workspace-folders{display:grid;gap:1rem;max-width:900px;margin:auto;padding:1rem}.workspace-folders header{display:flex;justify-content:space-between;gap:1rem}.workspace-folders p{margin:0}.workspace-folders header p,nav span{color:var(--color-text-muted,#64748b)}nav{display:grid;gap:.5rem}nav button{text-align:left;padding:.8rem;border:1px solid var(--color-border,#cbd5e1);border-radius:.5rem;background:var(--color-surface,#fff)}nav span{display:block;font-size:.85rem}@media(max-width:700px){.workspace-folders header{flex-wrap:wrap}}</style>
