<script setup lang="ts">
import axios from 'axios';
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import UiAlert from '../design-system/UiAlert.vue';
import UiButton from '../design-system/UiButton.vue';
import UiField from '../design-system/UiField.vue';
import type { WorkspaceSurface } from '../workspace/workspaceTypes';

const props = defineProps<{ surface: WorkspaceSurface }>();
const { t } = useI18n();
const base = computed(() => `/api/v1/tenants/${encodeURIComponent(props.surface.tenantId ?? 0)}/authorization/advanced`);
const processing = ref(false); const message = ref(''); const error = ref('');
const policyKey = ref(''); const policyPermissionId = ref(''); const policyMaximum = ref(''); const firstPermissionId = ref(''); const secondPermissionId = ref('');
const delegatorUserId = ref(''); const recipientUserId = ref(''); const delegationPermissionId = ref(''); const originAssignmentId = ref(''); const startsAt = ref(''); const endsAt = ref('');
const ownerUserId = ref(''); const identityName = ref(''); const purpose = ref(''); const identityPermissionId = ref(''); const identityId = ref(''); const credentialName = ref(''); const apiKey = ref('');
const temporaryPermissionId = ref(''); const temporaryStartsAt = ref(''); const temporaryEndsAt = ref(''); const accessRequests = ref<Array<{ id: number; permissionId: number; state: string; endsAt: string | null }>>([]);

function label(key: string): string { return t(`access.authorization.advancedControls.${key}`); }
function number(value: string): number | null { const parsed = Number(value); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : null; }
async function execute(action: () => Promise<void>, success: string): Promise<void> { processing.value = true; error.value = ''; message.value = ''; try { await action(); message.value = label(success); } catch { error.value = label('requestFailed'); } finally { processing.value = false; } }
async function publishPolicy(): Promise<void> { const permissionId = number(policyPermissionId.value); const maximum = Number(policyMaximum.value); if (!policyKey.value.trim() || !permissionId || !Number.isFinite(maximum) || maximum < 0) return; await execute(async () => { const policy = (await axios.post(`${base.value}/policies`, { key: policyKey.value.trim(), definition: { all: [{ type: 'AMOUNT_MAXIMUM', maximum }] } })).data.policy; await axios.post(`${base.value}/policies/${encodeURIComponent(policy.id)}/bindings`, { permissionId }); }, 'policyPublished'); }
async function createSeparationRule(): Promise<void> { const permissionId = number(firstPermissionId.value); const incompatiblePermissionId = number(secondPermissionId.value); if (!permissionId || !incompatiblePermissionId || permissionId === incompatiblePermissionId) return; await execute(() => axios.post(`${base.value}/separation-rules`, { permissionId, incompatiblePermissionId }), 'separationCreated'); }
async function createDelegation(): Promise<void> { const delegator = number(delegatorUserId.value); const recipient = number(recipientUserId.value); const permission = number(delegationPermissionId.value); const origin = number(originAssignmentId.value); if (!delegator || !recipient || !permission || !origin || !startsAt.value || !endsAt.value) return; await execute(() => axios.post(`${base.value}/delegations`, { delegatorUserId: delegator, recipientUserId: recipient, permissionId: permission, originAssignmentId: origin, startsAt: new Date(startsAt.value).toISOString(), endsAt: new Date(endsAt.value).toISOString() }), 'delegationCreated'); }
async function createIdentity(): Promise<void> { const owner = number(ownerUserId.value); const permissionId = number(identityPermissionId.value); if (!owner || !permissionId || !identityName.value.trim() || !purpose.value.trim()) return; await execute(async () => { const identity = (await axios.post(`${base.value}/service-identities`, { ownerUserId: owner, displayName: identityName.value.trim(), purpose: purpose.value.trim() })).data.serviceIdentity; await axios.post(`${base.value}/service-identities/${encodeURIComponent(identity.id)}/permissions`, { permissionId }); identityId.value = String(identity.id); }, 'identityCreated'); }
async function issueCredential(): Promise<void> { const id = number(identityId.value); if (!id || !credentialName.value.trim()) return; await execute(async () => { apiKey.value = String((await axios.post(`${base.value}/service-identities/${encodeURIComponent(id)}/credentials`, { displayName: credentialName.value.trim() })).data.apiKey ?? ''); }, 'credentialIssued'); }
async function loadAccessRequests(): Promise<void> { try { const response = await axios.get(`${base.value}/access-requests`); accessRequests.value = Array.isArray(response.data?.accessRequests) ? response.data.accessRequests.filter((item: unknown): item is { id: number; permissionId: number; state: string; endsAt: string | null } => typeof item === 'object' && item !== null && Number.isSafeInteger((item as { id?: unknown }).id) && Number.isSafeInteger((item as { permissionId?: unknown }).permissionId) && typeof (item as { state?: unknown }).state === 'string') : []; } catch { error.value = label('requestFailed'); } }
async function requestTemporaryAccess(): Promise<void> { const permissionId = number(temporaryPermissionId.value); if (!permissionId || !temporaryStartsAt.value || !temporaryEndsAt.value) return; await execute(async () => { await axios.post(`${base.value}/access-requests`, { permissionId, startsAt: new Date(temporaryStartsAt.value).toISOString(), endsAt: new Date(temporaryEndsAt.value).toISOString() }); await loadAccessRequests(); }, 'temporaryRequested'); }
async function changeAccessRequest(id: number, action: 'approval' | 'revocation', success: string): Promise<void> { await execute(async () => { await axios.post(`${base.value}/access-requests/${id}/${action}`); await loadAccessRequests(); }, success); }
onMounted(() => { void loadAccessRequests(); });
</script>

<template>
    <section class="authorization-administration" :aria-busy="processing">
        <details class="authorization-administration__advanced-disclosure">
            <summary>{{ label('title') }}</summary>
            <div class="authorization-administration__advanced-content">
                <h3>{{ label('title') }}</h3>
                <UiAlert v-if="error" tone="error">{{ error }}</UiAlert><UiAlert v-if="message" tone="success">{{ message }}</UiAlert>
                <section class="authorization-administration__form"><form @submit.prevent="publishPolicy"><h4>{{ label('policy') }}</h4><UiField id="advanced-policy-key" :label="label('policyKey')" required v-slot="field"><input id="advanced-policy-key" v-model.trim="policyKey" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-policy-permission" :label="label('permissionId')" required v-slot="field"><input id="advanced-policy-permission" v-model="policyPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-policy-maximum" :label="label('maximum')" required v-slot="field"><input id="advanced-policy-maximum" v-model="policyMaximum" type="number" min="0" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ label('publishPolicy') }}</UiButton></form><form @submit.prevent="createSeparationRule"><h4>{{ label('separation') }}</h4><UiField id="advanced-sod-first" :label="label('firstPermission')" required v-slot="field"><input id="advanced-sod-first" v-model="firstPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-sod-second" :label="label('incompatiblePermission')" required v-slot="field"><input id="advanced-sod-second" v-model="secondPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ label('createRule') }}</UiButton></form></section>
        <section class="authorization-administration__form"><form @submit.prevent="createDelegation"><h4>{{ label('delegation') }}</h4><UiField id="advanced-delegator" :label="label('delegator')" required v-slot="field"><input id="advanced-delegator" v-model="delegatorUserId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-recipient" :label="label('recipient')" required v-slot="field"><input id="advanced-recipient" v-model="recipientUserId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-delegation-permission" :label="label('permissionId')" required v-slot="field"><input id="advanced-delegation-permission" v-model="delegationPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-origin" :label="label('originAssignment')" required v-slot="field"><input id="advanced-origin" v-model="originAssignmentId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-delegation-start" :label="label('startsAt')" required v-slot="field"><input id="advanced-delegation-start" v-model="startsAt" type="datetime-local" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-delegation-end" :label="label('endsAt')" required v-slot="field"><input id="advanced-delegation-end" v-model="endsAt" type="datetime-local" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ label('createDelegation') }}</UiButton></form></section>
        <section class="authorization-administration__form"><form @submit.prevent="requestTemporaryAccess"><h4>{{ t('access.authorization.temporaryAccess') }}</h4><p>{{ t('access.authorization.temporaryAccessHelp') }}</p><UiField id="authorization-temporary-permission" :label="label('permissionId')" required v-slot="field"><input id="authorization-temporary-permission" v-model="temporaryPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="authorization-temporary-starts-at" :label="label('startsAt')" required v-slot="field"><input id="authorization-temporary-starts-at" v-model="temporaryStartsAt" type="datetime-local" :aria-describedby="field.describedBy" required></UiField><UiField id="authorization-temporary-ends-at" :label="label('endsAt')" required v-slot="field"><input id="authorization-temporary-ends-at" v-model="temporaryEndsAt" type="datetime-local" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ t('access.authorization.requestTemporaryAccess') }}</UiButton></form><h4>{{ t('access.authorization.accessRequestQueue') }}</h4><p v-if="!accessRequests.length">{{ t('access.authorization.emptyAccessRequests') }}</p><ul v-else><li v-for="request in accessRequests" :key="request.id">{{ request.state }}<UiButton v-if="request.state === 'PENDING'" variant="secondary" @click="changeAccessRequest(request.id, 'approval', 'temporaryApproved')">{{ t('access.authorization.approve') }}</UiButton><UiButton v-if="request.state === 'APPROVED'" variant="secondary" @click="changeAccessRequest(request.id, 'revocation', 'temporaryRevoked')">{{ t('access.authorization.revoke') }}</UiButton></li></ul></section>
                <section class="authorization-administration__form"><form @submit.prevent="createIdentity"><h4>{{ label('serviceIdentity') }}</h4><UiField id="advanced-owner" :label="label('responsibleUser')" required v-slot="field"><input id="advanced-owner" v-model="ownerUserId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-identity-name" :label="label('name')" required v-slot="field"><input id="advanced-identity-name" v-model.trim="identityName" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-identity-purpose" :label="label('purpose')" required v-slot="field"><input id="advanced-identity-purpose" v-model.trim="purpose" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-identity-permission" :label="label('permissionId')" required v-slot="field"><input id="advanced-identity-permission" v-model="identityPermissionId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ label('createIdentity') }}</UiButton></form><form @submit.prevent="issueCredential"><h4>{{ label('issueCredential') }}</h4><UiField id="advanced-identity-id" :label="label('identityId')" required v-slot="field"><input id="advanced-identity-id" v-model="identityId" inputmode="numeric" :aria-describedby="field.describedBy" required></UiField><UiField id="advanced-credential-name" :label="label('credentialName')" required v-slot="field"><input id="advanced-credential-name" v-model.trim="credentialName" :aria-describedby="field.describedBy" required></UiField><UiButton type="submit" :loading="processing">{{ label('issueCredential') }}</UiButton></form><UiAlert v-if="apiKey" tone="warning"><code>{{ apiKey }}</code></UiAlert></section>
            </div>
        </details>
    </section>
</template>
