<script setup lang="ts">
import axios from 'axios';
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import UiAlert from '../design-system/UiAlert.vue';
import UIRinoButton from '../design-system/UIRinoButton.vue';
import UiDialog from '../design-system/UiDialog.vue';

interface Execution { state: string; triggerType: string; startedAt: string; completedAt: string | null; summary: string | null; createdCount: number | null; updatedCount: number | null; details?: Record<string, number | string | null>; }
interface Audit { performedByUserId: number; action: string; outcome: string; occurredAt: string; }
interface Routine { routineKey: string; title: string; description: string; state: string; scheduleDescription: string; capabilities: { canSynchronize: boolean }; lastExecution?: Execution | null; executionHistory?: Execution[]; administrativeAudits?: Audit[]; }

const { t, locale } = useI18n();
const routines = ref<Routine[]>([]); const selected = ref<Routine | null>(null); const loading = ref(true); const processing = ref(false); const confirmationOpen = ref(false); const error = ref(''); const feedback = ref(''); const offline = ref(!navigator.onLine); const stale = ref(false); const selectedState = ref('ALL'); const mobileListVisible = ref(true); const detailTitle = ref<HTMLElement | null>(null);
const availableStates = computed(() => [...new Set(routines.value.map((routine) => routine.state))]);
const visibleRoutines = computed(() => selectedState.value === 'ALL' ? routines.value : routines.value.filter((routine) => routine.state === selectedState.value));
const selectedHistory = computed(() => selected.value?.executionHistory ?? []); const selectedAudits = computed(() => selected.value?.administrativeAudits ?? []); const hasPreviousData = computed(() => routines.value.length > 0);
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat(locale.value, { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const isIbgeTerritoryRoutine = (routine: Routine | null | undefined) => routine?.routineKey === 'locality-ibge-territory-catalog';
function routineTitle(routine: Routine): string { return isIbgeTerritoryRoutine(routine) ? t('access.maintenance.ibgeTerritory.title') : routine.title; }
function routineDescription(routine: Routine): string { return isIbgeTerritoryRoutine(routine) ? t('access.maintenance.ibgeTerritory.description') : routine.description; }
function routineSchedule(routine: Routine): string { return isIbgeTerritoryRoutine(routine) ? t('access.maintenance.ibgeTerritory.schedule') : routine.scheduleDescription; }
function executionSummary(execution: Execution): string {
    if (execution.state === 'FAILED') return t(isIbgeTerritoryRoutine(selected.value) ? 'access.maintenance.ibgeTerritory.synchronizationFailed' : 'access.maintenance.synchronizationFailed');
    if (execution.state === 'SUCCEEDED') return isIbgeTerritoryRoutine(selected.value)
        ? t('access.maintenance.ibgeTerritory.synchronizationSucceeded')
        : t('access.maintenance.synchronizationSucceeded', { created: execution.createdCount ?? 0, updated: execution.updatedCount ?? 0 });

    return execution.summary ?? t('access.maintenance.actionAccepted');
}
function markOnline() { offline.value = false; } function markOffline() { offline.value = true; } function errorMessage() { return offline.value ? t('access.maintenance.offline') : t('access.maintenance.loadFailed'); }
async function loadDetail(key: string): Promise<void> { try { selected.value = (await axios.get(`/api/v1/platform/maintenance/routines/${encodeURIComponent(key)}`)).data.routine; stale.value = false; mobileListVisible.value = false; await nextTick(); detailTitle.value?.focus(); } catch { stale.value = Boolean(selected.value); error.value = errorMessage(); } }
async function reload(preserveFeedback = false): Promise<void> { loading.value = true; error.value = ''; if (!preserveFeedback) feedback.value = ''; if (offline.value) { error.value = errorMessage(); loading.value = false; stale.value = hasPreviousData.value; return; } try { routines.value = (await axios.get('/api/v1/platform/maintenance/routines')).data.routines; if (!routines.value.length) { selected.value = null; return; } const preferred = visibleRoutines.value.some((routine) => routine.routineKey === selected.value?.routineKey) ? selected.value?.routineKey : visibleRoutines.value[0]?.routineKey ?? routines.value[0]!.routineKey; if (preferred) await loadDetail(preferred); } catch { stale.value = hasPreviousData.value; error.value = errorMessage(); } finally { loading.value = false; } }
async function selectRoutine(routine: Routine): Promise<void> { feedback.value = ''; await loadDetail(routine.routineKey); }
function applyStateFilter(): void { if (!visibleRoutines.value.some((routine) => routine.routineKey === selected.value?.routineKey)) { selected.value = null; mobileListVisible.value = true; } }
async function synchronize(): Promise<void> { if (!selected.value || offline.value) return; processing.value = true; feedback.value = ''; try { const response = await axios.post(`/api/v1/platform/maintenance/routines/${encodeURIComponent(selected.value.routineKey)}/actions/SYNCHRONIZE`); feedback.value = response.data.execution ? executionSummary(response.data.execution) : t('access.maintenance.actionAccepted'); confirmationOpen.value = false; await reload(true); } catch (reason) { const code = axios.isAxiosError(reason) ? reason.response?.data?.error?.code : ''; feedback.value = code === 'MAINTENANCE_ALREADY_RUNNING' ? t('access.maintenance.alreadyRunning') : t('access.maintenance.actionFailed'); } finally { processing.value = false; } }
onMounted(() => { window.addEventListener('online', markOnline); window.addEventListener('offline', markOffline); void reload(); }); onBeforeUnmount(() => { window.removeEventListener('online', markOnline); window.removeEventListener('offline', markOffline); });
</script>

<template>
  <main class="maintenance-hub" aria-labelledby="maintenance-title">
    <header class="maintenance-hub__header"><div><p class="maintenance-hub__eyebrow">{{ t('access.maintenance.eyebrow') }}</p><h2 id="maintenance-title" tabindex="-1">{{ t('access.maintenance.title') }}</h2></div><UIRinoButton variant="secondary" :loading="loading" :disabled="offline" @click="reload()" label="access.maintenance.reload" /></header>
    <div class="maintenance-hub__announcements" aria-live="polite"><UiAlert v-if="offline" tone="warning">{{ t('access.maintenance.offline') }}</UiAlert><UiAlert v-if="error" tone="error">{{ error }}</UiAlert><UiAlert v-if="stale" tone="warning">{{ t('access.maintenance.stale') }}</UiAlert><UiAlert v-if="feedback" tone="success">{{ feedback }}</UiAlert></div>
    <p v-if="loading && !hasPreviousData" aria-live="polite">{{ t('access.maintenance.loading') }}</p><p v-else-if="!loading && !routines.length" class="maintenance-hub__empty">{{ t('access.maintenance.empty') }}</p>
    <div v-else class="maintenance-hub__layout" :class="{ 'maintenance-hub__layout--detail': !mobileListVisible }">
      <aside class="maintenance-hub__list" :class="{ 'maintenance-hub__list--hidden-mobile': !mobileListVisible }"><label class="maintenance-hub__filter"><span>{{ t('access.maintenance.stateFilter') }}</span><select v-model="selectedState" @change="applyStateFilter"><option value="ALL">{{ t('access.maintenance.allStates') }}</option><option v-for="state in availableStates" :key="state" :value="state">{{ state }}</option></select></label><nav :aria-label="t('access.maintenance.routines')"><button v-for="routine in visibleRoutines" :key="routine.routineKey" type="button" :aria-current="selected?.routineKey === routine.routineKey ? 'page' : undefined" :class="{ selected: selected?.routineKey === routine.routineKey }" @click="selectRoutine(routine)"><strong>{{ routineTitle(routine) }}</strong><span>{{ routine.state }} · {{ routineSchedule(routine) }}</span></button></nav><p v-if="!visibleRoutines.length">{{ t('access.maintenance.filterEmpty') }}</p></aside>
<section v-if="selected" class="maintenance-hub__detail" aria-live="polite"><header><div><UIRinoButton class="maintenance-hub__back" variant="secondary" @click="mobileListVisible = true" label="access.maintenance.backToRoutines" /><h3 ref="detailTitle" tabindex="-1">{{ routineTitle(selected) }}</h3><p>{{ routineDescription(selected) }}</p></div><UIRinoButton v-if="selected.capabilities.canSynchronize" data-testid="maintenance-synchronize" :loading="processing" :disabled="offline" @click="confirmationOpen = true" variant="primary" label="access.maintenance.updateNow" /></header><dl><dt>{{ t('access.maintenance.state') }}</dt><dd>{{ selected.state }}</dd><dt>{{ t('access.maintenance.schedule') }}</dt><dd>{{ routineSchedule(selected) }}</dd><dt>{{ t('access.maintenance.lastExecution') }}</dt><dd>{{ date(selected.lastExecution?.completedAt ?? selected.lastExecution?.startedAt) }}</dd></dl><h4>{{ t('access.maintenance.technicalHistory') }}</h4><div class="maintenance-hub__records"><article v-for="execution in selectedHistory" :key="`${execution.startedAt}-${execution.triggerType}`"><strong>{{ execution.state }}</strong><span>{{ execution.triggerType }} · {{ date(execution.startedAt) }}</span><p>{{ executionSummary(execution) }}</p></article><p v-if="!selectedHistory.length">{{ t('access.maintenance.historyEmpty') }}</p></div><h4>{{ t('access.maintenance.administrativeAudit') }}</h4><div class="maintenance-hub__records"><article v-for="audit in selectedAudits" :key="`${audit.performedByUserId}-${audit.occurredAt}`"><strong>{{ audit.action }}</strong><span>{{ audit.outcome }} · {{ date(audit.occurredAt) }}</span></article><p v-if="!selectedAudits.length">{{ t('access.maintenance.auditEmpty') }}</p></div></section>
      <section v-else class="maintenance-hub__detail maintenance-hub__detail--empty"><p>{{ t('access.maintenance.selectRoutine') }}</p></section>
    </div>
    <UiDialog v-model="confirmationOpen" :title="t('access.maintenance.confirmTitle')" contained><p>{{ t('access.maintenance.confirmDescription') }}</p><UiAlert v-if="offline" tone="warning">{{ t('access.maintenance.offline') }}</UiAlert><div class="maintenance-hub__dialog-actions"><UIRinoButton :disabled="processing" @click="confirmationOpen = false" command="cancel"  /><UIRinoButton :loading="processing" :disabled="offline" @click="synchronize" variant="primary" label="access.maintenance.confirmAction" /></div></UiDialog>
  </main>
</template>

<style scoped>
.maintenance-hub { display:grid; gap:1rem; max-width:1200px; margin:auto; padding:1rem; }.maintenance-hub__header,.maintenance-hub__detail > header { display:flex; align-items:flex-start; justify-content:space-between; gap:1rem; }.maintenance-hub__eyebrow { margin:0; font-size:.82rem; color:var(--color-text-muted, #64748b); }h2,h3,h4 { margin:.15rem 0; }h3:focus { outline:2px solid var(--color-primary, #2563eb); outline-offset:3px; }.maintenance-hub__announcements { display:grid; gap:.5rem; }.maintenance-hub__layout { display:grid; grid-template-columns:minmax(15rem, .7fr) 2fr; gap:1rem; }.maintenance-hub__list { display:grid; align-content:start; gap:.75rem; }.maintenance-hub__filter { display:grid; gap:.3rem; font-weight:600; }.maintenance-hub__filter select { min-height:2.5rem; border:1px solid var(--color-border, #cbd5e1); border-radius:.4rem; padding:.35rem; background:var(--color-surface, #fff); }nav { display:grid; align-content:start; gap:.5rem; }nav button { text-align:left; border:1px solid var(--color-border, #cbd5e1); border-radius:.6rem; background:var(--color-surface, #fff); padding:.75rem; cursor:pointer; }nav button.selected { border-color:var(--color-primary, #2563eb); box-shadow:0 0 0 2px color-mix(in srgb, var(--color-primary, #2563eb) 20%, transparent); }nav span,.maintenance-hub__records span { display:block; color:var(--color-text-muted, #64748b); font-size:.85rem; }dl { display:grid; grid-template-columns:max-content 1fr; gap:.45rem 1rem; }dt { font-weight:600; }dd { margin:0; }.maintenance-hub__records { display:grid; gap:.5rem; }.maintenance-hub__records article { border-top:1px solid var(--color-border, #cbd5e1); padding:.65rem 0; }.maintenance-hub__records p { margin:.25rem 0 0; }.maintenance-hub__back { display:none; }.maintenance-hub__dialog-actions { display:flex; justify-content:flex-end; flex-wrap:wrap; gap:.75rem; margin-top:1rem; }@media (max-width: 700px) { .maintenance-hub__layout { grid-template-columns:1fr; }.maintenance-hub__layout--detail .maintenance-hub__list--hidden-mobile { display:none; }.maintenance-hub__header,.maintenance-hub__detail > header { flex-wrap:wrap; }.maintenance-hub__back { display:inline-flex; margin-bottom:.75rem; }.maintenance-hub__detail { min-width:0; }.maintenance-hub__records article { border:1px solid var(--color-border, #cbd5e1); border-radius:.5rem; padding:.65rem; } }
@media (min-width: 701px) and (max-width: 900px) { .maintenance-hub__layout { grid-template-columns:1fr; }.maintenance-hub__list nav { grid-template-columns:repeat(auto-fit, minmax(16rem, 1fr)); } }
</style>

<style scoped>
.maintenance-hub__filter select { border-color: var(--component-field-border); background: var(--component-field-background); }
</style>
